Repository cocotb/cocotb, pull requests merged in 2019-04, with the labels that each got.

#688 Add support for Cadence Xcelium, based on the existing IUS support.
  cocotb/share/makefiles/simulators/Makefile.xcelium
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_cocotb/test_cocotb.py
  tests/test_cases/test_iteration_mixedlang/test_iteration.py
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
  tests/test_cases/test_iteration_vhdl/test_iteration.py
Labels: category:simulators, status:ready-for-merge

#881 Update documation with package installation instructions
  README.md
  documentation/source/quickstart.rst
Labels: category:docs

#886 Rename context for clarity.
  cocotb/share/include/cocotb_utils.h
  cocotb/share/lib/simulator/simulatormodule.c
  cocotb/share/lib/utils/cocotb_utils.c
Labels: type:feature

#895 Update io.c
  examples/endian_swapper/cosim/io.c
Labels: status:changes-requested
