Repository cocotb/cocotb, pull requests merged in 2019-12, with the labels that each got.

#1223 object.__getattr__ does not exist
  cocotb/handle.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: type:bug

#1229 Ensure handle docstrings are inherited
  cocotb/handle.py
Labels: category:docs

#1205 Doc improvements, fixes
  cocotb/triggers.py
  documentation/source/introduction.rst
Labels: category:docs

#1231 Deprecate the `log.colour` attribute
  cocotb/log.py
Labels: type:deprecation

#1243 Add info about plusargs to doc.
  cocotb/__init__.py
  documentation/source/building.rst
  documentation/source/library_reference.rst
Labels: category:docs

#1213 Use a free function for `_log_from_c`
  cocotb/log.py
  cocotb/share/lib/embed/gpi_embed.c
  cocotb/share/lib/gpi_log/gpi_logging.c
  cocotb/share/lib/vpi/VpiImpl.cpp
Labels: type:cleanup

#1267 Added -std=c++11 to Makefile.verilator to support older gcc
  cocotb/share/makefiles/simulators/Makefile.verilator
Labels: category:simulators, type:bug

#1171 Fix race condition when external threads make function calls
  cocotb/scheduler.py
  tests/test_cases/test_external/test_external.py
Labels: category:core, type:bug
