Repository cocotb/cocotb, pull requests merged in 2019-03, with the labels that each got.

#783 Remove IUS option -sv which is detrimental to AMS
  cocotb/share/makefiles/simulators/Makefile.ius
Labels: category:simulators, status:needs-rebase

#849 Fix for python 3.7 (remove StopIteration)
  cocotb/handle.py
Labels: type:bug

#858 fix #857
  cocotb/__init__.py
  cocotb/regression.py
  cocotb/scheduler.py
  tests/test_cases/issue_857/Makefile
  tests/test_cases/issue_857/issue_857.py
Labels: status:changes-requested, type:bug

#785 Add support for SystemVerilog strings.
  cocotb/share/lib/vpi/VpiImpl.cpp
  tests/designs/sample_module/sample_module.sv
  tests/test_cases/test_discovery/test_discovery.py
Labels: type:feature

#825 Add tab completion for newer IPython.
  cocotb/handle.py
  tests/test_cases/test_discovery/test_discovery.py
Labels: status:changes-requested, type:feature

#842 Add osx and more python versions to travis (linux)
  .travis.yml
Labels: category:packaging

#790 Make things decorated with `cocotb.test` actually instances of `cocotb.test`
  cocotb/decorators.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: status:changes-requested

#788 Mostly fix 637
  cocotb/scheduler.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: status:changes-requested

#633 Add support for async/await
  cocotb/decorators.py
  cocotb/triggers.py
  documentation/source/coroutines.rst
  tests/test_cases/test_cocotb/test_cocotb.py
  tests/test_cases/test_cocotb/test_cocotb_35.py
Labels: status:changes-requested

#846 Add argv information for VHPI
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
  cocotb/share/makefiles/simulators/Makefile.aldec
  tests/designs/plusargs_module/Makefile
  tests/designs/plusargs_module/tb_top.vhd
  tests/test_cases/test_plusargs/plusargs.py
Labels: status:changes-requested

#876 Update README.md with install instruction
  README.md
Labels: category:docs

#859 Add ghdl to travis
  .travis.yml
  tox.ini
Labels: category:simulators, status:on-hold

#883 Change makefiles to use realpath function.
  cocotb/share/makefiles/Makefile.inc
  makefiles/Makefile.inc
  makefiles/Makefile.sim
Labels: category:windows, status:ready-for-merge
