Repository cocotb/cocotb, pull requests merged in 2019-08, with the labels that each got.

#1036 Add option start_high to Clock.start().
  cocotb/clock.py
Labels: status:ready-for-merge, type:feature

#1042 Extend cut off message. Fix spelling.
  cocotb/share/lib/simulator/simulatormodule.c
Labels: status:ready-for-merge, type:cleanup

#1054 Use -i/-m instead of -a/-e with GHDL
  cocotb/share/makefiles/simulators/Makefile.ghdl
Labels: category:simulators, status:ready-for-merge

#1052 Renamed dec_viterbi_ent to avoid collision with library.
  tests/designs/viterbi_decoder_axi4s/Makefile
  tests/designs/viterbi_decoder_axi4s/src/dec_viterbi.vhd
  tests/designs/viterbi_decoder_axi4s/src/generic_sp_ram.vhd
  tests/test_cases/test_iteration_vhdl/Makefile
Labels: category:tests-ci, status:ready-for-merge

#1058 Use only Sphinx 2.1 (some sphinxcontrib-trio features moved there).
  documentation/requirements.txt
  documentation/source/conf.py
Labels: category:docs, status:ready-for-merge

#1044 Extend docs. Restore clock behaviour before last change.
  examples/dff/tests/dff_cocotb.py
Labels: status:ready-for-merge

#1086 BUG: Fix inverted condition on the log filter
  cocotb/share/lib/gpi_log/gpi_logging.c
Labels: type:bug

#1053 Add COCOTB_RESULTS_FILE environment variable
  cocotb/regression.py
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.nvc
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.xcelium
  documentation/source/building.rst
  tests/test_cases/issue_253/Makefile
Labels: type:feature
