Repository cocotb/cocotb, pull requests merged in 2019-11, with the labels that each got.

#1168 Rename libvhpi to libcocotbvhpi.
  cocotb/share/lib/Makefile
  cocotb/share/lib/vhpi/Makefile
  cocotb/share/lib/vhpi/VhpiImpl.cpp
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.xcelium
Labels: category:core

#1177 Pull docs for fork()/scheduler.add() into Sphinx for linking.
  cocotb/triggers.py
  documentation/source/library_reference.rst
Labels: category:docs

#1179 Add scheduler module to library reference.
  cocotb/__init__.py
  documentation/source/library_reference.rst
Labels: category:docs

#1160 Added bus_separator to BusDriver
  cocotb/drivers/__init__.py
Labels: type:feature

#1192 Fix Avalon Memory with byteenable using Python 3
  cocotb/drivers/avalon.py
Labels: type:bug

#1173 Push external/function code out of decorators.py and into the scheduler
  cocotb/decorators.py
  cocotb/scheduler.py
Labels: type:cleanup

#1172 Add custom clocking example to docstring of Clock().
  cocotb/clock.py
Labels: category:docs

#1196 Store the version-number more simply
  Makefile
  cocotb/__init__.py
  cocotb/_version.py
  cocotb/config.py
  cocotb/share/makefiles/Makefile.sim
  documentation/source/building.rst
  documentation/source/conf.py
  setup.py
  version
Labels: category:docs, category:packaging

#1203 Fix error when ending test with assert in forked coorutine
  cocotb/scheduler.py
Labels: category:core

#1116 Users can specify an expected error type on tests
  cocotb/decorators.py
  cocotb/regression.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: category:core, status:ready-for-merge, type:feature
