Repository cocotb/cocotb, pull requests merged in 2019-07, with the labels that each got.

#974 Issue #253: Make VpiImpl::get_root_handle() return a GPI_MODULE always
  cocotb/share/lib/vpi/VpiImpl.cpp
Labels: status:on-hold

#980 Extract closure functions to a private method, so that `cocotb.coroutine.__new__` is not invoked each time
  cocotb/triggers.py
Labels: category:performance

#998 Fix random ZeroDivisionError
  cocotb/regression.py
Labels: type:bug
