Repository cocotb/cocotb, pull requests merged in 2020-09, with the labels that each got.

#2038 Fix GHDL Makefile for builds with multiple libraries
  cocotb/share/makefiles/simulators/Makefile.ghdl
Labels: category:simulators:ghdl

#2050 Remove outdated Sorter example from docs
  documentation/source/examples.rst
  documentation/source/newsfragments/2049.removal.rst
Labels: category:docs, type:cleanup

#2052 Describe GUI option for ModelSim
  documentation/source/simulator_support.rst
Labels: category:docs

#1502 Add matrix_multiplier to examples.
  documentation/source/examples.rst
  documentation/source/newsfragments/1502.doc.rst
  examples/Makefile
  examples/matrix_multiplier/hdl/matrix_multiplier.sv
  examples/matrix_multiplier/hdl/matrix_multiplier.vhd
  examples/matrix_multiplier/hdl/matrix_multiplier_pkg.vhd
  examples/matrix_multiplier/tests/Makefile
  examples/matrix_multiplier/tests/test_matrix_multiplier.py
Labels: category:performance, status:needs-review

#1051 Analog Mixed Signal Example
  documentation/source/diagrams/svg/example_regulator.svg
  documentation/source/diagrams/svg/example_rescap.svg
  documentation/source/diagrams/xml/example_regulator.xml
  documentation/source/diagrams/xml/example_rescap.xml
  documentation/source/examples.rst
  documentation/source/newsfragments/1051.feature.rst
  documentation/source/regulator.png
  documentation/source/regulator.rst
  documentation/source/rescap.png
  documentation/source/rescap.rst
  examples/mixed_signal/.gitignore
  examples/mixed_signal/hdl/analog_probe_cadence.sv
  examples/mixed_signal/hdl/analog_probe_synopsys.sv
  examples/mixed_signal/hdl/capacitor.vams
  examples/mixed_signal/hdl/nettypes_pkg_cadence.sv
  examples/mixed_signal/hdl/nettypes_pkg_synopsys.sv
  examples/mixed_signal/hdl/regulator.sv
  examples/mixed_signal/hdl/regulator.vams
  examples/mixed_signal/hdl/regulator_block.vams
  examples/mixed_signal/hdl/rescap.sv
  examples/mixed_signal/hdl/resistor.vams
  examples/mixed_signal/hdl/tb_regulator.sv
  examples/mixed_signal/hdl/tb_rescap.sv
  examples/mixed_signal/tests/Makefile
  examples/mixed_signal/tests/run.scs
  examples/mixed_signal/tests/test_regulator_plot.py
  examples/mixed_signal/tests/test_regulator_trim.py
  examples/mixed_signal/tests/test_rescap.py
  examples/mixed_signal/tests/test_rescap_minimalist.py
  examples/mixed_signal/tests/vcsAD.init
Labels: category:simulators:ius, category:simulators:xcelium, type:feature

#2078 Add info about diagrams.net saving to GitHub
  documentation/source/diagrams/README.md
Labels: category:docs

#2077 Detail content of _def_name and _def_file
  cocotb/handle.py
Labels: category:docs

#2086 Document envvar COCOTB_LIBRARY_COVERAGE.
  documentation/source/building.rst
Labels: category:docs
