Repository cocotb/cocotb, pull requests merged in 2020-03, with the labels that each got.

#1378 Add timescale to Aldec `alog`
  cocotb/share/makefiles/simulators/Makefile.aldec
Labels: category:simulators, status:needs-proprietary-testing, type:feature

#1471 Document variable SCRIPT_FILE
  cocotb/share/makefiles/Makefile.sim
  documentation/source/building.rst
Labels: category:docs

#1475 Fix newsfragment categories (bug -> bugfix)
  documentation/source/newsfragments/1253.bugfix.rst
  documentation/source/newsfragments/1314.bugfix.rst
  documentation/source/newsfragments/1410.bugfix.rst
Labels: category:docs, type:bug

#1441 Add --python-bin to cocotb-config
  cocotb/config.py
Labels: type:feature

#1465 Fix Sphinx warnings
  documentation/source/conf.py
Labels: category:docs, type:cleanup

#1385 Add a pull request template for GitHub
  .github/PULL_REQUEST_TEMPLATE.md
Labels: category:docs

#1430 Define __STDC_FORMAT_MACROS for old libc versions
  cocotb/_build_libs.py
Labels: category:core

#1511 Remove `BinaryValue.get_hex_buff` which is nonsense
  cocotb/binary.py
  documentation/source/newsfragments/1511.removal.rst
Labels: type:bug

#1520 Remove unnecessary __await__ call when creating async-based coroutines
  cocotb/decorators.py
Labels: type:cleanup

#1516 Better error messages when accidentally using yield in coroutines
  cocotb/decorators.py
  cocotb/scheduler.py
  tests/test_cases/test_cocotb/Makefile
  tests/test_cases/test_cocotb/test_async_generators.py
Labels: category:core, type:feature

#1517 Updated tests and examples to use installed makefiles, not the ones pointed to by $COCOTB
  tests/designs/array_module/Makefile
  tests/designs/avalon_module/Makefile
  tests/designs/avalon_streaming_module/Makefile
  tests/designs/basic_hierarchy_module/Makefile
  tests/designs/close_module/Makefile
  tests/designs/multi_dimension_array/Makefile
  tests/designs/plusargs_module/Makefile
  tests/designs/sample_module/Makefile
  tests/designs/uart2bus/Makefile
  tests/designs/vhdl_configurations/Makefile
  tests/designs/viterbi_decoder_axi4s/Makefile
  tests/test_cases/test_iteration_verilog/Makefile
Labels: category:tests-ci, type:cleanup

#1515 Fix test name in regression summary
  cocotb/regression.py
Labels: type:bug

#1518 Fix doctests in cocotb.binary, and run them as part of the regression test
  cocotb/binary.py
  tests/test_cases/test_cocotb/Makefile
  tests/test_cases/test_cocotb/test_doctests.py
Labels: category:tests-ci

#1457 Add custom entry point to load libraries (via GPI_EXTRA)
  cocotb/share/lib/gpi/GpiCommon.cpp
  cocotb/share/makefiles/Makefile.sim
  documentation/source/building.rst
  documentation/source/newsfragments/1457.feature.rst
Labels: status:ready-for-merge, type:feature

#1524 Replace type comments with type annotation
  cocotb/scheduler.py
Labels: Py3K, type:cleanup

#1534 Add pytest to CI
  .gitignore
  setup.cfg
  tests/pytest/test_binary_value.py
  tests/test_cases/test_cocotb/test_cocotb.py
  tox.ini
Labels: category:tests-ci

#1535 Remove unused entrypoint.vhdl file
  cocotb/share/lib/fli/entrypoint.vhdl
Labels: type:cleanup

#1536 Remove flake8 ignores on blank lines
  setup.cfg
Labels: category:tests-ci

#1359 Set some expect_error for Cadence simulators
  tests/test_cases/issue_120/issue_120.py
  tests/test_cases/issue_142/issue_142.py
  tests/test_cases/issue_348/issue_348.py
  tests/test_cases/test_discovery/test_discovery.py
  tests/test_cases/test_external/test_external.py
Labels: category:tests-ci

#1479 Implement coverage for verilator
  cocotb/share/lib/verilator/verilator.cpp
  documentation/source/simulator_support.rst
Labels: category:simulators

#1532 Add support for using Lock objects in async with
  cocotb/triggers.py
  documentation/source/newsfragments/1031.feature.rst
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: type:feature

#1545 Fix the XGMII monitor to work correctly on raw bytes
  cocotb/drivers/xgmii.py
  cocotb/monitors/xgmii.py
  documentation/source/newsfragments/1545.bugfix.rst
Labels: Py3K, type:bug

#1546 Minor cleanups to the amba driver
  cocotb/drivers/amba.py
Labels: Py3K, type:cleanup
