Repository cocotb/cocotb, pull requests merged in 2020-12, with the labels that each got.

#1987 Provide <SimName>Version classes to compare simulator versions
  .github/workflows/regression-tests.yml
  cocotb/_sim_versions.py
  setup.cfg
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:simulators, type:feature

#2254 Documentation cleanup
  cocotb/scheduler.py
  cocotb/share/include/gpi.h
  documentation/.gitignore
  documentation/Doxyfile
  documentation/source/conf.py
  documentation/source/index.rst
  documentation/source/library_reference_c.rst
  documentation/source/release_notes.rst
Labels: category:docs, type:cleanup

#2257 Use Verilator's --timescale option
  cocotb/share/makefiles/simulators/Makefile.verilator
Labels: category:codebase:project-automation, category:simulators:verilator

#2256 Add test for writing and reading from struct members
  tests/designs/sample_module/sample_module.sv
  tests/test_cases/test_array_simple/test_array_simple.py
Labels: category:tests-ci

#2203 Deprecated cocotb.utils.pack and cocotb.utils.unpack
  cocotb/handle.py
  cocotb/utils.py
  documentation/source/newsfragments/2203.removal.rst
  tests/pytest/test_utils.py
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: type:deprecation

#2263 Fix error on dynamic libpython loading on mac
  cocotb_build_libs.py
Labels: category:OS:MacOS

#2265 Remove erroneous assignment to input port
  tests/designs/sample_module/sample_module.sv
  tests/test_cases/test_array_simple/test_array_simple.py
Labels: type:bug

#2105 Update the verilator main control loop.
  cocotb/share/lib/verilator/verilator.cpp
  cocotb/share/makefiles/simulators/Makefile.verilator
  documentation/source/newsfragments/2105.change.rst
  documentation/source/simulator_support.rst
  tests/test_cases/issue_1279/Makefile
  tests/test_cases/test_exit_error/Makefile
Labels: category:simulators:verilator

#2287 Use the lowest possible Python version for 3.5-3.7 in CI
  .github/workflows/regression-tests.yml
Labels: category:tests-ci

#2285 Differentiate docs for stable and latest version more
  README.md
  documentation/source/install.rst
  documentation/source/install_devel.rst
Labels: category:docs

#2292 Use Python 3.7.1 which is new on GitHub Actions
  .github/workflows/regression-tests.yml
Labels: category:tests-ci

#2090 Updates to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: category:docs

#2301 Remove unused Dockerfile
  Dockerfile
Labels: type:cleanup

#2305 Fix example code for rotating logger
  documentation/source/rotating_logger.rst
Labels: category:docs, type:bug

#2306 Use '<=' in places where 'dut.sig = val' was used
  documentation/source/quickstart.rst
  examples/endian_swapper/hal_tests/test_endian_swapper_hal.py
  examples/mean/tests/test_mean.py
Labels: type:cleanup
