Repository cocotb/cocotb, pull requests merged in 2020-06, with the labels that each got.

#1864 Prevent AXI Lite tests from running when TOPLEVEL_LANG isn't verilog
  examples/axi_lite_slave/tests/Makefile
Labels: category:tests-ci, type:bug

#1910 combine_results.py: xml.etree.cElementTree removed in Python 3.9
  bin/combine_results.py
Labels: category:core, type:cleanup

#1915 Force an up-to-date virtualenv to avoid CI warnings
  .travis.yml
Labels: category:tests-ci

#1924 Document TOPLEVEL_LANG
  documentation/source/building.rst
Labels: category:docs

#1931 Skip mixed_language example if TOPLEVEL_LANG is not Verilog.
  examples/mixed_language/tests/Makefile
Labels: category:tests-ci, status:needs-review

#1890 Deprecate implicit conversion of handle values to strings.
  cocotb/handle.py
  tests/test_cases/issue_348/issue_348.py
  tests/test_cases/test_cocotb/test_deprecated.py
  tests/test_cases/test_cocotb/test_edge_triggers.py
  tests/test_cases/test_discovery/test_discovery.py
Labels: type:bug

#1935 add share/lib/verilator/verilator.cpp to package
  setup.py
Labels: category:packaging, type:bug
