Repository cocotb/cocotb, pull requests merged in 2020-05, with the labels that each got.

#1741 Use raw string for docstring with escape codes
  tests/test_cases/test_array/test_array.py
Labels: category:tests-ci, type:cleanup

#1620 Add dff_simple example
  examples/Makefile
  examples/simple_dff/.gitignore
  examples/simple_dff/Makefile
  examples/simple_dff/dff.sv
  examples/simple_dff/dff.vhdl
  examples/simple_dff/test_dff.py
Labels: category:docs

#1747 Add info to CONTRIBUTING.md that examples should get the CC0/PD SPDX header
  CONTRIBUTING.md
Labels: category:docs

#1751 Enable flake8 for examples and tests
  examples/axi_lite_slave/tests/test_axi_lite_slave.py
  examples/dff/tests/dff_cocotb.py
  examples/endian_swapper/tests/test_endian_swapper.py
  examples/ping_tun_tap/tests/test_icmp_reply.py
  setup.cfg
  tests/pytest/test_binary_value.py
  tests/test_cases/issue_120/issue_120.py
  tests/test_cases/issue_134/test_integers.py
  tests/test_cases/issue_134/test_reals.py
  tests/test_cases/issue_142/issue_142.py
  tests/test_cases/issue_253/issue_253.py
  tests/test_cases/issue_330/issue_330.py
  tests/test_cases/issue_348/issue_348.py
  tests/test_cases/issue_588/issue_588.py
  tests/test_cases/issue_768_a/issue_768.py
  tests/test_cases/issue_893/issue_893.py
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_array_simple/test_array_simple.py
  tests/test_cases/test_avalon/test_avalon.py
  tests/test_cases/test_avalon_stream/test_avalon_stream.py
  tests/test_cases/test_cocotb/test_generator_coroutines.py
  tests/test_cases/test_cocotb/test_handle.py
  tests/test_cases/test_cocotb/test_scheduler.py
  tests/test_cases/test_cocotb/test_tests.py
  tests/test_cases/test_configuration/test_configurations.py
  tests/test_cases/test_discovery/test_discovery.py
  tests/test_cases/test_discovery/test_vhdl_block.py
  tests/test_cases/test_discovery/test_vhdl_indexed_name.py
  tests/test_cases/test_exit_error/test_exit.py
  tests/test_cases/test_external/test_external.py
  tests/test_cases/test_iteration_mixedlang/test_iteration.py
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
  tests/test_cases/test_iteration_vhdl/test_iteration.py
  tests/test_cases/test_multi_dimension_array/test_cocotb_array.py
  tests/test_cases/test_plusargs/plusargs.py
  tests/test_cases/test_verilog_access/test_verilog_access.py
  tests/test_cases/test_vhdl_access/test_vhdl_access.py
Labels: category:tests-ci, type:cleanup

#1753 Remove E302, E303, E305 from flake8 ignore list
  cocotb/_py_compat.py
  cocotb/binary.py
  cocotb/bus.py
  cocotb/clock.py
  cocotb/decorators.py
  cocotb/drivers/__init__.py
  cocotb/drivers/amba.py
  cocotb/drivers/avalon.py
  cocotb/handle.py
  cocotb/log.py
  cocotb/monitors/avalon.py
  cocotb/result.py
  cocotb/scheduler.py
  cocotb/triggers.py
  cocotb/utils.py
  cocotb/wavedrom.py
  cocotb_build_libs.py
  examples/axi_lite_slave/tests/test_axi_lite_slave.py
  examples/dff/tests/dff_cocotb.py
  examples/simple_dff/test_dff.py
  setup.cfg
  setup.py
  tests/pytest/test_binary_value.py
  tests/test_cases/issue_253/issue_253.py
  tests/test_cases/issue_330/issue_330.py
  tests/test_cases/issue_348/issue_348.py
  tests/test_cases/issue_588/issue_588.py
  tests/test_cases/issue_768_a/issue_768.py
  tests/test_cases/issue_768_b/issue_768.py
  tests/test_cases/issue_892/issue_892.py
  tests/test_cases/issue_893/issue_893.py
  tests/test_cases/issue_957/issue_957.py
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_array_simple/test_array_simple.py
  tests/test_cases/test_avalon/test_avalon.py
  tests/test_cases/test_avalon_stream/test_avalon_stream.py
  tests/test_cases/test_cocotb/test_deprecated.py
  tests/test_cases/test_configuration/test_configurations.py
  tests/test_cases/test_discovery/test_discovery.py
  tests/test_cases/test_discovery/test_vhdl_indexed_name.py
  tests/test_cases/test_exit_error/test_exit.py
  tests/test_cases/test_external/test_external.py
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
  tests/test_cases/test_iteration_vhdl/test_iteration.py
  tests/test_cases/test_multi_dimension_array/test_cocotb_array.py
  tests/test_cases/test_verilog_access/test_verilog_access.py
  tests/test_cases/test_vhdl_access/test_vhdl_access.py
Labels: category:tests-ci, type:cleanup

#1765 Move issue_134 tests
  tests/test_cases/issue_134/Makefile
  tests/test_cases/issue_134/test_integers.py
  tests/test_cases/issue_134/test_reals.py
  tests/test_cases/test_cocotb/test_handle.py
Labels: category:tests-ci

#1649 Add support for launching IPython
  cocotb/ipython_support.py
  documentation/requirements.txt
  documentation/source/newsfragments/1649.feature.rst
  documentation/source/troubleshooting.rst
  examples/dff/tests/Makefile
Labels: type:feature

#1714 Fixes for libs on MacOS
  cocotb_build_libs.py
Labels: category:packaging, status:changes-requested

#1784 Make expect_error more specific and link Icarus issue
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:simulators, category:tests-ci

#1777 Fix warning/error of Verilator linter
  tests/designs/sample_module/sample_module.sv
Labels: category:tests-ci, type:cleanup

#1692 Introduce SIM=riviera, keep SIM=aldec as deprecated alias
  cocotb/share/makefiles/Makefile.deprecations
  cocotb/share/makefiles/simulators/Makefile.riviera
  documentation/source/newsfragments/1691.change.rst
  documentation/source/simulator_support.rst
Labels: category:simulators, type:cleanup

#1791 Remove E128 from flake8 ignore list
  cocotb/drivers/amba.py
  cocotb/triggers.py
  examples/mean/tests/test_mean.py
  setup.cfg
  tests/test_cases/test_discovery/test_discovery.py
Labels: type:cleanup

#1590 Mention proper way of setting make vars
  documentation/source/building.rst
  documentation/source/troubleshooting.rst
Labels: category:docs

#1797 Remove unused includes in embed.h
  cocotb/share/include/embed.h
Labels: type:cleanup

#1780 Use last scheduled write to set handle value
  cocotb/handle.py
  cocotb/scheduler.py
  tests/test_cases/test_cocotb/test_scheduler.py
Labels: category:core, type:bug

#1732 Add howto section "Rotating Log Files"
  cocotb/log.py
  documentation/source/index.rst
  documentation/source/newsfragments/1400.doc.rst
  documentation/source/rotating_logger.rst
Labels: category:docs, type:feature

#1806 Fix segfault due to uninitialized PyTypeObject
  cocotb/share/lib/simulator/simulatormodule.cpp
Labels: type:bug

#1781 Avoid calling gpi_load_extra_libs reentrantly
  cocotb/share/lib/embed/gpi_embed.cpp
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/lib/gpi/GpiCommon.cpp
  cocotb/share/lib/vhpi/VhpiImpl.cpp
  cocotb/share/lib/vpi/VpiImpl.cpp
Labels: type:cleanup

#1346 Use InternalError rather than assertion
  cocotb/decorators.py
Labels: category:core, type:bug

#1634 Add test for accessing _underscore_name
  cocotb/handle.py
  tests/designs/sample_module/sample_module.sv
  tests/test_cases/test_cocotb/test_handle.py
Labels: category:tests-ci, type:bug

#1679 Split installation instructions out of quickstart
  README.md
  documentation/requirements.txt
  documentation/source/conf.py
  documentation/source/genindex.rst
  documentation/source/index.rst
  documentation/source/install.rst
  documentation/source/install_devel.rst
  documentation/source/newsfragments/1445.change.rst
  documentation/source/py-modindex.rst
  documentation/source/quickstart.rst
Labels: category:docs

#1808 Fix contact information
  setup.py
Labels: category:packaging, type:cleanup

#1813 Fix doc rendering problem at NO_COLOR
  documentation/source/building.rst
Labels: category:docs, type:bug

#1816 Remove duplicate always block and fix alignment
  tests/designs/sample_module/sample_module.sv
Labels: type:cleanup

#1823 Remove nonexisting PYTHON_FILES as a dependency
  cocotb/share/makefiles/simulators/Makefile.vcs
Labels: type:cleanup

#1811 Give more context when truncating a `BinaryValue`
  cocotb/binary.py
  tests/pytest/test_binary_value.py
Labels: type:feature

#1818 Update news fragments with makefile changes
  documentation/source/newsfragments/1063.change.rst
Labels: category:docs

#1830 Use simple_dff as example in quickstart guide
  documentation/source/quickstart.rst
Labels: category:docs

#1824 Force doctest for `cocotb.utils` to run uncolored
  tests/test_cases/test_cocotb/test_doctests.py
Labels: category:tests-ci, type:bug

#1832 Update Questa makefile to support 2020 releases
  cocotb/share/makefiles/simulators/Makefile.questa
Labels: category:simulators, type:bug

#1817 Use isinstance to check for tests
  cocotb/regression.py
Labels: category:core, type:bug

#1825 Add cocotb.simulator to Python library reference
  documentation/source/library_reference.rst
Labels: category:docs, type:feature

#1837 Expose type objects in the `cocotb.simulator` namespace
  cocotb/share/lib/simulator/simulatormodule.cpp
Labels: category:docs

#1838 Add argument names to docstrings in cocotb.simulator
  cocotb/share/lib/simulator/simulatormodule.cpp
  cocotb/share/lib/simulator/simulatormodule.h
Labels: category:docs

#1845 Fix #1519 newsfragment to correctly display str
  documentation/source/newsfragments/1519.removal.rst
Labels: category:docs, type:cleanup

#1852 Fix type annotations on simulatormodule
  cocotb/share/lib/simulator/simulatormodule.cpp
Labels: category:docs

#1764 Move variable help text out of Makefile.sim
  cocotb/config.py
  cocotb/share/makefiles/Makefile.sim
  documentation/source/building.rst
Labels: category:docs, status:needs-rebase

#1849 drivers: Move type information from docstrings to annotations
  cocotb/drivers/__init__.py
  cocotb/drivers/amba.py
  cocotb/drivers/avalon.py
  cocotb/drivers/opb.py
  cocotb/drivers/xgmii.py
Labels: category:docs

#1835 Prevent printing summary multiple times
  cocotb/regression.py
Labels: category:core, type:bug

#1866 Disable failing tests on Riviera due to #1859
  tests/test_cases/issue_1279/issue_1279.py
  tests/test_cases/test_closedown/test_closedown.py
Labels: category:simulators:riviera, category:tests-ci

#1868 Improve Active-HDL makefile
  cocotb/share/makefiles/simulators/Makefile.activehdl
Labels: category:simulators:activehdl, type:bug

#1667 GPI cleanups inspired by a stale branch
  cocotb/share/lib/fli/FliImpl.h
  cocotb/share/lib/gpi/gpi_priv.h
  cocotb/share/lib/vpi/VpiImpl.h
Labels: type:cleanup

#1885 Fix typo in scoreboard error message
  cocotb/scoreboard.py
Labels: type:bug

#1869 Document non-working versions of Active-HDL
  documentation/source/simulator_support.rst
Labels: category:docs, category:simulators:activehdl

#1881 XGMII Monitor: using bytearray instead of bytes
  cocotb/monitors/xgmii.py
Labels: type:bug
