Repository cocotb/cocotb, pull requests merged in 2020-01, with the labels that each got.

#1274 Added --trace-structs to Makefile.verilator.
  cocotb/share/makefiles/simulators/Makefile.verilator
Labels: category:simulators

#1249 Added Waitable to the library reference.
  documentation/source/library_reference.rst
Labels: category:docs

#1236 Documentation improvements: add markup; tweak wording; fix typos
  cocotb/__init__.py
  cocotb/decorators.py
  cocotb/result.py
  cocotb/scheduler.py
  cocotb/share/include/sv_vpi_user.h
  cocotb/triggers.py
  documentation/Doxyfile
  documentation/source/building.rst
  documentation/source/hal_cosimulation.rst
  documentation/source/introduction.rst
  documentation/source/quickstart.rst
  documentation/source/simulator_support.rst
  documentation/source/troubleshooting.rst
  tests/test_cases/test_verilog_access/test_verilog_access.py
  tests/test_cases/test_vhdl_access/test_vhdl_access.py
Labels: category:docs

#1276 Improve documentation; fix typos.
  cocotb/clock.py
  cocotb/result.py
  cocotb/triggers.py
  cocotb/utils.py
Labels: category:docs

#1242 Fix plusargs testcase
  tests/designs/plusargs_module/Makefile
  tests/designs/plusargs_module/tb_top.vhd
Labels: type:bug

#1264 Fix with_timeout trigger
  cocotb/triggers.py
Labels: category:docs, type:feature

#1270 Update release_notes.rst
  documentation/source/release_notes.rst
Labels: category:docs

#751 Fix for handle class equality operators.
  cocotb/handle.py
  tests/designs/basic_hierarchy_module/Makefile
  tests/designs/basic_hierarchy_module/basic_hierarchy_module.v
  tests/test_cases/test_compare/Makefile
  tests/test_cases/test_compare/test_compare.py
Labels: type:bug

#1180 Allow dropping into interactive pdb shell when hitting exception. Ad…
  cocotb/regression.py
  documentation/source/building.rst
Labels: category:core, type:feature

#1301 Install swig on linux ci
  .travis.yml
Labels: category:tests-ci

#1288 Remove unnecessary __getattribute__ calls
  cocotb/handle.py
Labels: type:cleanup

#1304 Add documentation for the `cocotb-config` script.
  cocotb/config.py
  documentation/requirements.txt
  documentation/source/conf.py
  documentation/source/library_reference.rst
Labels: category:docs

#1268 Fix the broken log record accumulation
  cocotb/decorators.py
  cocotb/regression.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: category:performance, type:bug

#1327 Fix target $(COCOTB_RESULTS_FILE) by using a tab
  cocotb/share/makefiles/simulators/Makefile.vcs
Labels: category:simulators, type:bug

#1325 Correct expectation value, add comments
  tests/test_cases/test_array/test_array.py
Labels: category:tests-ci, type:bug

#1352 Fix compiler warnings in FliImpl
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/lib/fli/FliImpl.h
  cocotb/share/lib/fli/FliObjHdl.cpp
Labels: category:simulators

#1353 Don't log all 30k objects in the test
  tests/test_cases/test_iteration_vhdl/test_iteration.py
Labels: category:tests-ci

#1343 Fix: Use (lib)cocotbvhpi instead of (lib)vhpi
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.ius
Labels: category:simulators, type:bug
