Repository cocotb/cocotb, pull requests merged in 2020-08, with the labels that each got.

#1836 Support rpath-like "<probing privatePath='' />" on Windows
  cocotb/__init__.py
  cocotb/_os_compat.py
  cocotb/share/makefiles/Makefile.inc
  cocotb_build_libs.py
Labels: category:windows

#2019 Do not link explicitly with libstdc++
  cocotb_build_libs.py
Labels: type:cleanup

#2034 Align with currently used GitHub issue/PR labels
  CONTRIBUTING.md
Labels: category:docs

#2033 Add term BFM to glossary
  documentation/source/glossary.rst
Labels: category:docs

#2032 Add README explaining directory contents
  documentation/source/diagrams/README.md
Labels: category:docs

#2040 Add references to terms in glossary
  documentation/source/building.rst
  documentation/source/endian_swapper.rst
  documentation/source/examples.rst
  documentation/source/glossary.rst
  documentation/source/hal_cosimulation.rst
  documentation/source/index.rst
  documentation/source/install.rst
  documentation/source/ping_tun_tap.rst
  documentation/source/quickstart.rst
  documentation/source/simulator_support.rst
  documentation/source/testbench_tools.rst
  documentation/source/troubleshooting.rst
Labels: category:docs
