Repository cocotb/cocotb, pull requests merged in 2020-04, with the labels that each got.

#1557 Ensure source files are read as utf8, rather than a system-specific encoding.
  setup.py
Labels: category:tests-ci, type:bug

#1381 Change string type of handles to bytes
  cocotb/handle.py
  cocotb/share/lib/simulator/simulatormodule.cpp
  documentation/source/newsfragments/1381.removal.rst
  tests/test_cases/test_cocotb/test_cocotb.py
  tests/test_cases/test_cocotb/test_deprecated.py
  tests/test_cases/test_discovery/test_discovery.py
Labels: type:deprecation

#1496 Deprecate COCOTB_NVC_TRACE, with doc reference
  cocotb/share/makefiles/Makefile.deprecations
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.sim
  documentation/source/building.rst
  documentation/source/newsfragments/1495.removal.rst
  documentation/source/simulator_support.rst
Labels: category:docs, type:deprecation

#1425 Compile common libraries to single `libs` directory
  cocotb/_build_libs.py
  cocotb/handle.py
  cocotb/log.py
  cocotb/regression.py
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.nvc
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.verilator
  cocotb/share/makefiles/simulators/Makefile.xcelium
  cocotb/triggers.py
  cocotb/utils.py
  documentation/source/newsfragments/1425.change.rst
  examples/endian_swapper/tests/Makefile
  tests/test_cases/issue_253/Makefile
  tests/test_cases/test_multi_dimension_array/test_cocotb_array.py
Labels: type:cleanup

#1445 Better back compatibility and use cocotb-config
  Makefile
  cocotb/share/makefiles/Makefile.inc
  documentation/source/newsfragments/1445.change.rst
  documentation/source/quickstart.rst
  examples/endian_swapper/cosim/Makefile
  makefiles/Makefile.inc
  makefiles/Makefile.sim
  tests/Makefile
Labels: type:cleanup

#1523 Updated core libraries to use async/await
  cocotb/clock.py
  cocotb/decorators.py
  cocotb/regression.py
  cocotb/scheduler.py
  cocotb/triggers.py
  cocotb/wavedrom.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: type:cleanup

#1572 Add a readthedocs configuration file
  .readthedocs.yml
Labels: category:docs

#1577 Pin sphinx before version 3, until an upstream bug is fixed.
  documentation/requirements.txt
Labels: category:docs

#1564 Add documentation note for missing cocotb-config
  documentation/source/quickstart.rst
Labels: category:docs

#1578 Update modelsim.def to fix compilation errors
  cocotb/share/def/.gitignore
  cocotb/share/def/modelsim.def
Labels: category:windows, type:bug

#1583 Add a missing `static` on a private function
  cocotb/share/lib/embed/gpi_embed.cpp
Labels: type:cleanup

#1584 Use docs.cocotb.org for documentation
  README.md
  cocotb/__init__.py
Labels: category:docs

#1574 Set PYTHON_BIN using cocotb-config
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.pylib.Darwin
  cocotb/share/makefiles/Makefile.pylib.Linux
  cocotb/share/makefiles/Makefile.pylib.Msys
  documentation/source/newsfragments/1574.change.rst
Labels: type:cleanup

#1586 Use sets instead of dicts with meaningless values
  cocotb/handle.py
Labels: type:cleanup

#1587 Remove log lines that duplicate exception information.
  cocotb/handle.py
Labels: type:cleanup

#1589 Remove BinaryValue.__cmp__
  cocotb/binary.py
Labels: Py3K, type:cleanup

#1554 Improve test_discovery
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:tests-ci, type:cleanup

#1588 Improve windows support in Makefiles
  .gitignore
  cocotb/_build_libs.py
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.verilator
  examples/endian_swapper/tests/Makefile
  tests/test_cases/issue_253/Makefile
Labels: category:windows

#1595 Remove PYTHONPATH from the simulator invocation
  cocotb/__init__.py
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.nvc
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.verilator
  cocotb/share/makefiles/simulators/Makefile.xcelium
  examples/adder/tests/Makefile
  examples/endian_swapper/tests/Makefile
  tests/test_cases/issue_253/Makefile
Labels: type:cleanup

#1599 Align ghdl simulators with others based on #1063
  cocotb/share/makefiles/simulators/Makefile.ghdl
Labels: category:simulators, type:bug

#1598 Align Aldec simulators with others based on #1063
  .gitignore
  cocotb/share/makefiles/simulators/Makefile.aldec
Labels: category:simulators, type:bug, type:cleanup

#1576 Update docs for async/await syntax
  cocotb/triggers.py
  documentation/source/coroutines.rst
  documentation/source/quickstart.rst
  documentation/source/triggers.rst
Labels: Py3K, category:docs

#1606 Fix libraries runpath on newer Debian
  cocotb/_build_libs.py
Labels: category:packaging, type:bug

#1592 Address issues with unexpected MODULE values
  cocotb/__init__.py
  cocotb/regression.py
  tests/test_cases/test_module_var_empty/Makefile
  tests/test_cases/test_module_var_messy/Makefile
  tests/test_cases/test_module_var_messy/test_nothing.py
  tests/test_cases/test_module_without_tests/Makefile
  tests/test_cases/test_module_without_tests/test_nothing.py
Labels: type:feature

#1510 Remove HierarchyObject.__hasattr__
  cocotb/bus.py
  cocotb/handle.py
Labels: type:cleanup

#1596 Cleanup and fix tcl sources paths on Windows
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.questa
  examples/adder/tests/Makefile
  examples/mean/tests/Makefile
  examples/mixed_language/tests/Makefile
  examples/ping_tun_tap/tests/Makefile
  tests/designs/array_module/Makefile
  tests/designs/avalon_module/Makefile
  tests/designs/avalon_streaming_module/Makefile
  tests/designs/basic_hierarchy_module/Makefile
  tests/designs/close_module/Makefile
  tests/designs/multi_dimension_array/Makefile
  tests/designs/plusargs_module/Makefile
  tests/designs/sample_module/Makefile
  tests/designs/uart2bus/Makefile
  tests/designs/vhdl_configurations/Makefile
  tests/designs/viterbi_decoder_axi4s/Makefile
  tests/test_cases/test_iteration_verilog/Makefile
Labels: type:cleanup

#1609 Clean up leftover uses of WPWD
  examples/endian_swapper/tests/Makefile
  examples/mean/tests/Makefile
  examples/mixed_language/tests/Makefile
Labels: type:bug

#1529 Update README.md with a simple example
  README.md
Labels: category:docs

#1413 remove unused COCOTB_*_LIB* variables
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.nvc
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.verilator
  cocotb/share/makefiles/simulators/Makefile.xcelium
  tests/test_cases/issue_253/Makefile
Labels: type:cleanup

#1612 Deprecate VERILATOR_TRACE with doc reference
  cocotb/share/makefiles/Makefile.deprecations
  documentation/source/newsfragments/1495.removal.rst
Labels: category:docs, category:simulators

#1482 Restructure Documentation
  documentation/source/conf.py
  documentation/source/index.rst
  documentation/source/introduction.rst
  documentation/source/newsfragments/1482.doc.rst
  documentation/source/simulator_support.rst
Labels: category:docs, type:cleanup

#1623 Remove unused and undocumented Makefile variables.
  Makefile
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.sim
  tests/designs/avalon_module/Makefile
Labels: type:cleanup

#1624 Fix weird indentationn in sample_module
  tests/designs/sample_module/sample_module.sv
  tests/designs/sample_module/sample_module.vhdl
  tests/designs/sample_module/sample_module_1.vhdl
Labels: category:tests-ci, type:cleanup

#1619 Remove dependency on Makfiles in endian_swapper
  examples/endian_swapper/cosim/Makefile
Labels: type:cleanup

#1621 Remove NDEBUG from endian_swapper example
  examples/endian_swapper/cosim/Makefile
Labels: type:cleanup

#1628 Move `contributors` off the index page, as requested by a TODO
  documentation/source/contributors.rst
  documentation/source/further_resources.rst
  documentation/source/index.rst
Labels: category:docs

#1641 Unpin Sphinx and breathe
  documentation/requirements.txt
Labels: category:docs

#1614 Active hdl support
  cocotb/share/makefiles/simulators/Makefile.activehdl
  documentation/source/newsfragments/1601.feature.rst
  documentation/source/simulator_support.rst
Labels: category:simulators, category:windows, type:feature

#1646 Change __name__ to __qualname__ in base Python libraries
  cocotb/binary.py
  cocotb/bus.py
  cocotb/clock.py
  cocotb/decorators.py
  cocotb/drivers/__init__.py
  cocotb/handle.py
  cocotb/monitors/__init__.py
  cocotb/regression.py
  cocotb/scheduler.py
  cocotb/scoreboard.py
  cocotb/triggers.py
  cocotb/utils.py
Labels: Py3K, type:cleanup

#1644 GHDL support on Windows
  cocotb/_build_libs.py
  cocotb/share/def/ghdl.def
  cocotb/share/makefiles/simulators/Makefile.ghdl
Labels: category:simulators, category:windows

#1652 Make `gpi_iterator_hdl` objects natively iterable
  cocotb/handle.py
  cocotb/share/lib/simulator/simulatormodule.cpp
  cocotb/share/lib/simulator/simulatormodule.h
Labels: type:cleanup

#1635 Ensure simulators are launched in 32-bit mode with 32-bit python
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.xcelium
Labels: category:simulators

#1632 Remove unused Makefile.pylib files.
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.pylib
  cocotb/share/makefiles/Makefile.pylib.Darwin
  cocotb/share/makefiles/Makefile.pylib.Linux
  cocotb/share/makefiles/Makefile.pylib.Msys
  documentation/source/newsfragments/1632.removal.rst
Labels: type:cleanup

#1633 Add FOSSi Foundation to Contributors section
  documentation/source/conf.py
  documentation/source/contributors.rst
Labels: category:docs

#1637 Update installation instructions
  documentation/source/quickstart.rst
  documentation/source/simulator_support.rst
Labels: category:docs

#1615 Add tests for getting and setting `BinaryValue.buff`
  tests/pytest/test_binary_value.py
Labels: category:tests-ci

#1658 Tidy python bindings in the endian_swapper example
  examples/endian_swapper/cosim/io.c
Labels: Py3K, type:bug, type:cleanup

#1661 Ensure errors happen immediately when using delayed assignment
  cocotb/handle.py
  cocotb/scheduler.py
  documentation/source/newsfragments/1661.bugfix.rst
  tests/test_cases/test_cocotb/common.py
  tests/test_cases/test_cocotb/test_deprecated.py
  tests/test_cases/test_cocotb/test_handle.py
Labels: category:core, type:bug

#1664 Include function name in argument parsing error messages
  cocotb/share/lib/simulator/simulatormodule.cpp
Labels: type:feature

#1665 More small cleanups to the simulator extension module
  cocotb/share/lib/simulator/simulatormodule.cpp
  cocotb/share/lib/simulator/simulatormodule.h
Labels: type:cleanup

#1666 Remove dead code
  cocotb/share/lib/fli/FliObjHdl.cpp
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
Labels: type:cleanup

#1663 Show how to set SIM to start each simulator
  documentation/source/simulator_support.rst
Labels: category:docs

#1629 Rearrange Makefiles
  cocotb/share/makefiles/Makefile.inc
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.activehdl
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.nvc
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.verilator
  cocotb/share/makefiles/simulators/Makefile.xcelium
  documentation/source/newsfragments/1629.feature.rst
Labels: type:feature

#1669 Add subsection for CVC for completeness
  documentation/source/simulator_support.rst
Labels: category:docs

#1607 adding verilator waveform capability in documentation
  documentation/source/simulator_support.rst
Labels: category:docs

#1493 Simplify `cocotb.generators` to use builtins where possible
  cocotb/generators/__init__.py
Labels: type:cleanup

#1670 Replace link to removed "introduction" page
  README.md
Labels: category:docs

#1672 Fix include path in modelsim makefile
  cocotb/share/makefiles/simulators/Makefile.modelsim
Labels: type:bug

#1674 Cleanup of modelsim and questa makefiles
  cocotb/share/makefiles/simulators/Makefile.modelsim
  cocotb/share/makefiles/simulators/Makefile.questa
Labels: category:simulators, type:cleanup

#1668 Remove not needed includes of Makefile.inc
  README.md
  documentation/source/quickstart.rst
  examples/adder/tests/Makefile
  examples/axi_lite_slave/tests/Makefile
  examples/dff/tests/Makefile
  examples/endian_swapper/tests/Makefile
  examples/mean/tests/Makefile
  examples/mixed_language/tests/Makefile
  examples/ping_tun_tap/tests/Makefile
  makefiles/Makefile.inc
  tests/designs/array_module/Makefile
  tests/designs/avalon_module/Makefile
  tests/designs/avalon_streaming_module/Makefile
  tests/designs/basic_hierarchy_module/Makefile
  tests/designs/close_module/Makefile
  tests/designs/multi_dimension_array/Makefile
  tests/designs/plusargs_module/Makefile
  tests/designs/sample_module/Makefile
  tests/designs/uart2bus/Makefile
  tests/designs/vhdl_configurations/Makefile
  tests/designs/viterbi_decoder_axi4s/Makefile
  tests/test_cases/test_iteration_verilog/Makefile
Labels: type:cleanup

#1677 Update Icarus Verilog to version 10.3
  .travis.yml
  Dockerfile
Labels: category:tests-ci

#1678 Mention that new files should get the SPDX header
  CONTRIBUTING.md
Labels: category:docs

#1695 Ignore files that CVC produces
  .gitignore
Labels: category:simulators, type:cleanup

#1698 Remove explicit function signatures
  documentation/source/library_reference.rst
Labels: category:docs, type:cleanup

#1694 Remove NVC without deprecation phase
  cocotb/share/makefiles/Makefile.deprecations
  cocotb/share/makefiles/simulators/Makefile.nvc
  documentation/source/building.rst
  documentation/source/newsfragments/1495.removal.rst
  documentation/source/newsfragments/1693.removal.rst
  documentation/source/simulator_support.rst
  documentation/source/spelling_wordlist.txt
Labels: category:simulators, type:cleanup

#1696 Fix broken doc references
  documentation/source/coroutines.rst
Labels: category:docs, type:cleanup

#1684 Prevent killed coroutines from running in corner case
  cocotb/scheduler.py
  tests/test_cases/test_cocotb/test_scheduler.py
Labels: type:bug

#1702 Improve Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.ghdl
Labels: category:simulators, type:bug

#1711 Time unit and precision in Icarus
  cocotb/share/makefiles/simulators/Makefile.icarus
  documentation/source/simulator_support.rst
Labels: category:simulators

#1713 Remove COCOTB_SIM from makefiles
  cocotb/share/lib/gpi/GpiCommon.cpp
  cocotb/share/makefiles/simulators/Makefile.activehdl
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.verilator
  cocotb/share/makefiles/simulators/Makefile.xcelium
  tests/test_cases/issue_253/Makefile
Labels: type:cleanup

#1719 Move build_libs.py out of cocotb package
  MANIFEST.in
  cocotb_build_libs.py
  setup.py
Labels: category:packaging, type:cleanup

#1721 Fix path to test_discovery.py
  documentation/source/simulator_support.rst
Labels: category:docs, type:bug

#1723 Add is_set method to Event
  cocotb/triggers.py
  documentation/source/newsfragments/1723.feature.rst
  tests/test_cases/test_cocotb/test_concurrency_primitives.py
Labels: category:core, category:docs, status:needs-newsfragment, type:feature

#1726 Remove unused LIB_LOAD makefile variable.
  cocotb/share/makefiles/simulators/Makefile.activehdl
  cocotb/share/makefiles/simulators/Makefile.aldec
  tests/test_cases/issue_253/Makefile
Labels: type:cleanup

#1697 De-duplicate doc index entries
  documentation/source/library_reference.rst
Labels: category:docs, type:cleanup

#1685 Mention that this is the complete simulator list
  documentation/source/simulator_support.rst
Labels: category:docs

#1725 Add Questa/ModelSim error on missing FLI library
  cocotb/share/makefiles/simulators/Makefile.questa
Labels: category:simulators

#1706 Use conda to build documentation
  .readthedocs.yml
  documentation/conda.yml
  documentation/source/conf.py
Labels: category:docs

#1733 Remove obsolete comment about Icarus and COCOTB_HDL_TIME*
  documentation/source/building.rst
Labels: category:docs, type:cleanup

#1438 Honor NO_COLOR to disable colored output (#1309)
  cocotb/utils.py
  documentation/source/building.rst
  documentation/source/newsfragments/1309.feature.rst
Labels: status:changes-requested, type:feature

#1734 Document multiple newsfragment support.
  documentation/source/newsfragments/README.rst
Labels: category:docs

#1735 Change how cocotb is built for documentation
  documentation/Makefile
Labels: category:docs, type:bug
