Repository cocotb/cocotb, pull requests merged in 2020-10, with the labels that each got.

#2087 Link to deprecations in roadmap section
  documentation/source/roadmap.rst
Labels: category:docs

#2082 Fix GHA regression tests
  .github/workflows/regression-tests.yml
Labels: category:tests-ci

#2112 Fix some typos
  cocotb/share/lib/vpi/VpiImpl.cpp
Labels: type:cleanup

#2101 Print object type info in VpiSingleIterator
  cocotb/share/lib/vpi/VpiImpl.h
Labels: category:codebase:gpi, type:cleanup

#2118 Use realpath when ACTIVEHDL_BIN_DIR is set.
  cocotb/share/makefiles/simulators/Makefile.activehdl
Labels: category:codebase:project-automation, category:simulators:activehdl, type:bug

#2120 Use async/await syntax and assertions
  tests/test_cases/test_array/test_array.py
Labels: category:tests-ci, type:cleanup

#2123 Fix typo 'seqfault'
  tests/designs/close_module/Makefile
Labels: type:cleanup

#2116 Adapt number of discovered objects for Cadence Xcelium
  tests/test_cases/test_iteration_mixedlang/test_iteration.py
Labels: category:simulators:ius, category:simulators:xcelium, category:tests-ci

#2127 Remove explicit newlines, LOG_*() already end with one
  cocotb/share/include/cocotb_utils.h
  cocotb/share/lib/embed/gpi_embed.cpp
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/lib/fli/FliObjHdl.cpp
  cocotb/share/lib/utils/cocotb_utils.cpp
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
  cocotb/share/lib/vpi/VpiCbHdl.cpp
Labels: type:cleanup

#2114 Show Timer object reuse instead of re-creation
  documentation/source/coroutines.rst
Labels: category:docs

#2146 Remove shebang line and executable flag from test files
  tests/test_cases/test_avalon/test_avalon.py
  tests/test_cases/test_avalon_stream/test_avalon_stream.py
  tests/test_cases/test_closedown/test_closedown.py
  tests/test_cases/test_external/test_external.py
Labels: type:cleanup

#2147 Document that only VPI implements drivers/loads
  cocotb/handle.py
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/lib/vhpi/VhpiImpl.cpp
Labels: category:docs

#2128 Convert some but not all tests to async/await syntax
  tests/test_cases/test_avalon/test_avalon.py
  tests/test_cases/test_avalon_stream/test_avalon_stream.py
  tests/test_cases/test_closedown/test_closedown.py
  tests/test_cases/test_compare/test_compare.py
  tests/test_cases/test_configuration/test_configurations.py
  tests/test_cases/test_discovery/test_discovery.py
  tests/test_cases/test_discovery/test_vhdl_block.py
  tests/test_cases/test_discovery/test_vhdl_indexed_name.py
  tests/test_cases/test_exit_error/test_exit.py
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
  tests/test_cases/test_multi_dimension_array/test_cocotb_array.py
  tests/test_cases/test_plusargs/plusargs.py
  tests/test_cases/test_verilog_access/test_verilog_access.py
  tests/test_cases/test_vhdl_access/test_vhdl_access.py
Labels: category:tests-ci

#2134 Add global alias for DUT parameter
  cocotb/__init__.py
  documentation/source/building.rst
  documentation/source/library_reference.rst
  documentation/source/newsfragments/2134.feature.rst
  documentation/source/quickstart.rst
Labels: type:feature

#2130 Add configuration for stale bot
  .github/stale.yml
Labels: category:meta

#2102 imlement FST support for verilator
  cocotb/share/lib/verilator/verilator.cpp
  cocotb/share/makefiles/simulators/Makefile.verilator
  documentation/source/simulator_support.rst
Labels: category:codebase:project-automation, category:simulators:verilator, type:feature

#2143 GPI: iterate over parent if VPI gen scope array not found
  cocotb/handle.py
  cocotb/share/lib/vpi/VpiImpl.cpp
  documentation/source/newsfragments/2079.bugfix.rst
Labels: category:codebase:gpi, category:simulators:icarus, type:bug

#2164 Define TOPLEVEL_LANG before checking it
  examples/mixed_language/tests/Makefile
Labels: category:tests-ci

#2163 Use absolute path for VCS and compile as VHDL-93 for Xcelium
  tests/test_cases/test_fatal/Makefile
Labels: category:tests-ci

#2162 Fix lexer name for doctest examples
  documentation/source/quickstart.rst
Labels: category:docs

#2161 Mention LD_DEBUG=libs in Troubleshooting section
  documentation/source/troubleshooting.rst
Labels: category:docs

#2167 Improve contributors documentation on running tests locally
  CONTRIBUTING.md
  tox.ini
Labels: category:docs

#2165 Convert examples to use assert
  examples/axi_lite_slave/tests/test_axi_lite_slave.py
  examples/endian_swapper/tests/test_endian_swapper.py
  examples/mixed_language/tests/test_mixed_language.py
Labels: type:cleanup
