Repository cocotb/cocotb, pull requests merged in 2020-02, with the labels that each got.

#1341 Remove references to Python 2.7 from docs
  documentation/source/coroutines.rst
  documentation/source/quickstart.rst
Labels: Py3K

#1357 Fix "Time precision larger than unit" errors
  examples/dff/tests/Makefile
Labels: type:bug

#1321 Do not cause a stack overflow if logging fails
  cocotb/share/lib/gpi_log/gpi_logging.c
Labels: type:bug

#1266 Stop setting `logger.propagate=True` on every logger
  cocotb/__init__.py
  cocotb/decorators.py
  cocotb/log.py
Labels: type:cleanup, type:feature

#1149 Use the C++11 override keyword on virtual functions, for clarity.
  cocotb/share/lib/fli/FliImpl.h
  cocotb/share/lib/gpi/gpi_priv.h
  cocotb/share/lib/vhpi/VhpiImpl.h
  cocotb/share/lib/vpi/VpiImpl.h
Labels: type:cleanup

#1370 Fix incorrect use of tabs in makefiles
  cocotb/share/makefiles/Makefile.pylib.Linux
  cocotb/share/makefiles/Makefile.pylib.Msys
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.nvc
  cocotb/share/makefiles/simulators/Makefile.questa
Labels: type:bug

#1369 fix windows travis build
  .travis.yml
  Dockerfile.windows
Labels: category:tests-ci

#1300 Initialize the PWD variable only in sim makefile
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.verilator
Labels: category:simulators, status:changes-requested

#1358 Ignore errors of sub-makes; add .PHONY; fix help text
  Makefile
  tests/test_cases/test_array/Makefile
  tests/test_cases/test_multi_dimension_array/Makefile
Labels: type:bug

#1379 Fix UnboundLocalError if no tests run
  bin/combine_results.py
Labels: category:tests-ci, type:bug

#1366 Use PEP383 to embed non-decodable bytes in argv
  cocotb/share/lib/embed/gpi_embed.c
Labels: Py3K, type:bug

#1303 Add towncrier to maintain release notes
  CONTRIBUTING.md
  documentation/requirements.txt
  documentation/source/conf.py
  documentation/source/newsfragments/1255.feature.rst
  documentation/source/newsfragments/README.rst
  documentation/source/release_notes.rst
  pyproject.toml
Labels: category:docs, status:needs-review

#1376 Add missing release notes from previous PRs
  documentation/source/newsfragments/1180.feature.rst
  documentation/source/newsfragments/1253.bug.rst
  documentation/source/newsfragments/1266.feature.rst
  documentation/source/newsfragments/1282.feature.rst
  documentation/source/newsfragments/1314.bug.rst
Labels: category:docs

#1287 Eliminate indirection in NonHierarchyObject.value
  cocotb/handle.py
Labels: category:performance, type:cleanup

#1394 use pip3 to install tox on travis and Dockerfile
  .travis.yml
  Dockerfile
Labels: category:tests-ci

#1107 Add vpi Net type support
  cocotb/handle.py
  cocotb/share/lib/vpi/VpiCbHdl.cpp
  cocotb/share/lib/vpi/VpiImpl.cpp
  documentation/source/newsfragments/1107.feature.rst
  tests/designs/sample_module/sample_module.sv
  tests/test_cases/test_discovery/test_discovery.py
Labels: status:needs-newsfragment, type:feature

#1412 Add Sphinx docs for the non-deprecated logging functions and classes
  cocotb/log.py
  documentation/source/library_reference.rst
  documentation/source/newsfragments/1266.feature.rst
  documentation/source/testbench_tools.rst
Labels: category:docs

#1414 remove unused EXTRA_LIBS and EXTRA_LIBDIRS vars
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.questa
Labels: category:windows

#1417 Revert "remove PY_SO_LIB and do not try to load python dynamically"
  cocotb/_build_libs.py
  cocotb/share/lib/embed/gpi_embed.c
Labels: type:bug

#1410 Log non-string messages with colored log formatter
  cocotb/log.py
  documentation/source/newsfragments/1410.bug.rst
Labels: status:needs-newsfragment, type:bug

#1420 Ensure that the SimTimeContextFilter is actually applied correctly
  cocotb/log.py
Labels: type:bug

#1338 Simplify traceback propagation
  cocotb/decorators.py
  cocotb/outcomes.py
  cocotb/regression.py
  cocotb/scheduler.py
  cocotb/triggers.py
  cocotb/utils.py
Labels: Py3K, type:cleanup

#1421 Tidy vlog_startup_routines_bootstrap a little
  cocotb/share/lib/vpi/VpiImpl.cpp
Labels: type:cleanup

#1433 Replace while loop iteration with a for loop
  cocotb/handle.py
Labels: type:cleanup

#1403 Expose force/release to cocotb
  cocotb/handle.py
  cocotb/share/include/gpi.h
  cocotb/share/lib/fli/FliImpl.h
  cocotb/share/lib/fli/FliObjHdl.cpp
  cocotb/share/lib/gpi/GpiCommon.cpp
  cocotb/share/lib/gpi/gpi_priv.h
  cocotb/share/lib/simulator/simulatormodule.c
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
  cocotb/share/lib/vhpi/VhpiImpl.h
  cocotb/share/lib/vpi/VpiCbHdl.cpp
  cocotb/share/lib/vpi/VpiImpl.h
  documentation/source/library_reference.rst
  documentation/source/newsfragments/1403.feature.rst
  documentation/source/quickstart.rst
  tests/test_cases/test_force_release/Makefile
  tests/test_cases/test_force_release/test_force_release.py
Labels: type:feature

#1434 Remove uses of `_py_compat` which are no longer needed
  cocotb/_py_compat.py
  cocotb/binary.py
  cocotb/decorators.py
  cocotb/generators/bit.py
  cocotb/handle.py
  cocotb/outcomes.py
  cocotb/regression.py
  cocotb/result.py
  cocotb/scheduler.py
  cocotb/triggers.py
  cocotb/utils.py
  tests/test_cases/test_avalon_stream/test_avalon_stream.py
  tests/test_cases/test_cocotb/test_cocotb.py
Labels: Py3K, type:cleanup

#1429 Remove GpiClockHdl and its C accessor methods
  cocotb/share/lib/gpi/GpiCommon.cpp
  cocotb/share/lib/gpi/gpi_priv.h
Labels: type:cleanup

#1440 Remove the use of `ReturnValue` internally
  cocotb/decorators.py
  cocotb/drivers/amba.py
  cocotb/drivers/avalon.py
  cocotb/drivers/opb.py
  cocotb/monitors/__init__.py
  cocotb/scheduler.py
  cocotb/triggers.py
  documentation/source/hal_cosimulation.rst
Labels: Py3K, category:performance, type:cleanup

#1439 Cleanup code with "Python 2" comments
  cocotb/decorators.py
  cocotb/handle.py
  cocotb/scheduler.py
  cocotb/utils.py
  tests/test_cases/test_external/test_external.py
Labels: Py3K, type:cleanup

#1388 Derive doc link to use from cocotb version
  cocotb/share/makefiles/Makefile.sim
Labels: category:docs

#1444 Fix missing function arguments in FLI after #1403
  cocotb/share/lib/fli/FliImpl.h
Labels: type:bug

#1418 Rename libvpi to libcocotbvpi for consistency
  cocotb/_build_libs.py
  cocotb/share/lib/vpi/VpiImpl.cpp
  cocotb/share/makefiles/simulators/Makefile.aldec
  cocotb/share/makefiles/simulators/Makefile.cvc
  cocotb/share/makefiles/simulators/Makefile.ghdl
  cocotb/share/makefiles/simulators/Makefile.icarus
  cocotb/share/makefiles/simulators/Makefile.ius
  cocotb/share/makefiles/simulators/Makefile.questa
  cocotb/share/makefiles/simulators/Makefile.vcs
  cocotb/share/makefiles/simulators/Makefile.verilator
  cocotb/share/makefiles/simulators/Makefile.xcelium
  tests/test_cases/issue_253/Makefile
Labels: type:cleanup

#1377 Doc: add python debug strategy in troubleshooting section
  documentation/source/troubleshooting.rst
Labels: category:docs

#1467 Fix undefined reference in documentation
  documentation/source/library_reference.rst
  documentation/source/quickstart.rst
Labels: category:docs, type:bug
