Repository cocotb/cocotb, pull requests merged in 2020-07, with the labels that each got.

#1956 Mention Icarus versions not supporting bit access
  documentation/source/simulator_support.rst
Labels: category:docs

#1639 Document "private" members in cocotb.handle
  cocotb/handle.py
Labels: category:docs

#1498 Update VHPI callbacks
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
Labels: category:simulators, status:needs-proprietary-testing

#1961 fix vhdl error in adder example
  examples/adder/hdl/adder.vhdl
Labels: type:bug

#1877 Fix VHDL issues for Riviera-Pro to pass CI
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_cocotb/test_timing_triggers.py
Labels: category:tests-ci

#1828 Add Icarus master on Windows to CI
  .travis.yml
Labels: category:simulators:icarus, category:tests-ci

#1906 Use std::initializer_list in place of GpiIteratorMapping
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/lib/fli/FliImpl.h
  cocotb/share/lib/gpi/gpi_priv.h
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
  cocotb/share/lib/vhpi/VhpiImpl.h
  cocotb/share/lib/vpi/VpiCbHdl.cpp
  cocotb/share/lib/vpi/VpiImpl.h
Labels: type:cleanup

#1968 Add Glossary section
  documentation/source/glossary.rst
  documentation/source/index.rst
Labels: category:docs

#1969 Add link to 'good first issue' label
  documentation/source/roadmap.rst
Labels: category:docs

#1979 Add link to issues for the respective simulator
  documentation/source/simulator_support.rst
Labels: category:docs

#1991 Merge simulatormodule.h into simulatormodule.cpp
  cocotb/share/lib/simulator/simulatormodule.cpp
  cocotb/share/lib/simulator/simulatormodule.h
Labels: category:core, type:cleanup

#1975 Fix warning introduced by recent change
  cocotb/share/lib/fli/FliImpl.cpp
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
  cocotb/share/lib/vpi/VpiCbHdl.cpp
Labels: category:core, type:bug

#1970 Fix flake8 F841 reports for core code
  cocotb/__init__.py
  cocotb/config.py
  cocotb/drivers/amba.py
  cocotb/drivers/avalon.py
  cocotb/scheduler.py
  cocotb/utils.py
  cocotb/xunit_reporter.py
  setup.cfg
Labels: type:cleanup
