Repository cocotb/cocotb, pull requests merged in 2020-11, with the labels that each got.

#2179 Add more mentions of pip's --user option
  documentation/source/install.rst
  documentation/source/install_devel.rst
Labels: category:docs

#2177 Cleanup TestError
  cocotb/handle.py
  cocotb/result.py
  documentation/source/newsfragments/2177.removal.rst
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: type:cleanup

#2172 Add units='step'
  cocotb/clock.py
  cocotb/decorators.py
  cocotb/triggers.py
  cocotb/utils.py
  documentation/source/newsfragments/2171.feature.rst
  tests/test_cases/test_cocotb/test_handle.py
  tests/test_cases/test_cocotb/test_scheduler.py
  tests/test_cases/test_cocotb/test_timing_triggers.py
Labels: type:feature

#2181 Add config for pylint
  .pylintrc
Labels: type:cleanup

#2182 Clean up some pylint findings
  cocotb/drivers/__init__.py
  cocotb/regression.py
  cocotb/scheduler.py
Labels: type:cleanup

#2191 Add pass_total value for VCS in test_array.test_discover_all
  tests/test_cases/test_array/test_array.py
Labels: category:simulators:vcs, category:tests-ci

#2199 Upload coverage results to codecov
  .github/workflows/regression-tests.yml
Labels: category:tests-ci, type:feature

#2206 Reduce number of operations per stale action from 30 to 5
  .github/workflows/stale.yml
Labels: category:tests-ci

#2201 Deprecate cocotb.hook
  cocotb/decorators.py
  documentation/source/building.rst
  documentation/source/newsfragments/2201.removal.rst
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: category:codebase:test-runner, type:deprecation

#2212 Mention Verilog's join/join_any in triggers.py
  cocotb/triggers.py
Labels: category:docs

#1248 Add AXI4Master driver
  cocotb/drivers/amba.py
  documentation/source/library_reference.rst
  examples/axi_lite_slave/hdl/axi_lite_demo.v
  examples/axi_lite_slave/tests/test_axi_lite_slave.py
  tests/designs/axi4_ram/Makefile
  tests/designs/axi4_ram/README.md
  tests/designs/axi4_ram/arbiter.v
  tests/designs/axi4_ram/axi_interconnect.v
  tests/designs/axi4_ram/axi_ram.v
  tests/designs/axi4_ram/axi_register.v
  tests/designs/axi4_ram/axi_register_rd.v
  tests/designs/axi4_ram/axi_register_wr.v
  tests/designs/axi4_ram/priority_encoder.v
  tests/designs/axi4_ram/top.v
  tests/test_cases/test_axi4/Makefile
  tests/test_cases/test_axi4/test_axi4.py
Labels: category:extensions, type:feature

#2200 Increase coverage in xunit_reporter.py
  cocotb/xunit_reporter.py
  documentation/source/newsfragments/2200.removal.rst
  tests/test_cases/test_failure/Makefile
  tests/test_cases/test_failure/test_failure.py
Labels: type:cleanup

#2155 Add gcov/gcovr to GHA for C++ code coverage collection
  .github/workflows/regression-tests.yml
  cocotb_build_libs.py
  tox.ini
Labels: category:tests-ci

#2219 Make docstring for BinaryValue.is_resolvable clearer
  cocotb/binary.py
Labels: category:docs

#2211 gitpod: Run verilator with trace, improve general usability
  .gitpod.yml
  .theia/settings.json
Labels: category:meta

#2148 Improve VHPI logging output and some comments
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
  cocotb/share/lib/vhpi/VhpiImpl.cpp
Labels: type:cleanup

#2175 Add support for adding sets of parameters with TestFactory.add_option
  cocotb/regression.py
  documentation/source/newsfragments/2175.feature.rst
  tests/test_cases/test_cocotb/Makefile
  tests/test_cases/test_cocotb/test_testfactory.py
Labels: type:feature

#2221 Improve _compat_mapping deprecation warnings
  cocotb/handle.py
  examples/axi_lite_slave/tests/test_axi_lite_slave.py
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: type:cleanup

#2229 Allow tuning of matrix_multiplier test length in tox environment
  tox.ini
Labels: category:tests-ci

#2188 Fix deprecation warning for str(handle)
  cocotb/handle.py
  cocotb/share/lib/vpi/VpiCbHdl.cpp
  tests/test_cases/issue_330/issue_330.py
  tests/test_cases/test_discovery/test_discovery.py
Labels: type:cleanup

#2235 Fix some sphinx warnings
  cocotb/decorators.py
  cocotb/drivers/amba.py
  cocotb/monitors/__init__.py
  documentation/source/install_devel.rst
  documentation/source/release_notes.rst
Labels: type:cleanup

#2237 Remove test_doctests and use 'pytest --doctest-modules' instead
  setup.cfg
  tests/test_cases/test_cocotb/Makefile
  tests/test_cases/test_cocotb/test_doctests.py
Labels: type:cleanup

#2228 Remove dead code in utils.py
  cocotb/utils.py
Labels: type:deprecation

#2243 Cleanup matrix_multiplier example
  examples/matrix_multiplier/hdl/matrix_multiplier.sv
  examples/matrix_multiplier/tests/Makefile
  examples/matrix_multiplier/tests/test_matrix_multiplier.py
Labels: category:tests-ci, type:cleanup
