Repository cocotb/cocotb, pull requests merged in 2021-11, with the labels that each got.

#2494 Add support for managing coroutines in with_timeout
  cocotb/triggers.py
  documentation/source/newsfragments/2494.change.rst
  tests/test_cases/test_cocotb/test_timing_triggers.py
Labels: type:feature, category:codebase:scheduler

#2760 Remove CoroutineComplete.
  cocotb/decorators.py
  cocotb/scheduler.py
Labels: type:cleanup, category:codebase:scheduler

#2775 Implement Force/Release for FLI
  cocotb/share/lib/fli/FliObjHdl.cpp
  documentation/source/newsfragments/2775.feature.rst
  tests/test_cases/test_force_release/test_force_release.py
Labels: category:simulators:questa
