Repository cocotb/cocotb, pull requests merged in 2021-02, with the labels that each got.

#2329 Add test for reading and writing ANSI-colored strings
  tests/designs/sample_module/sample_module.sv
  tests/designs/sample_module/sample_module.vhdl
  tests/test_cases/test_cocotb/test_handle.py
Labels: category:tests-ci

#2383 Point to 'latest' docs for install-devel
  documentation/source/install.rst
  documentation/source/install_devel.rst
  documentation/source/quickstart.rst
Labels: category:docs

#2409 Improve Verilator doc section
  documentation/source/simulator_support.rst
Labels: category:docs

#2340 Add section 'Extending existing Simulation Setups' for each simulator
  documentation/source/custom_flows.rst
  documentation/source/index.rst
  documentation/source/newsfragments/2340.doc.rst
  documentation/source/simulator_support.rst
Labels: category:docs

#2411 Add documentation checkers, do spellchecking
  cocotb/binary.py
  cocotb/generators/__init__.py
  cocotb/generators/byte.py
  cocotb/handle.py
  cocotb/ipython_support.py
  cocotb/share/lib/simulator/simulatormodule.cpp
  cocotb/triggers.py
  cocotb/utils.py
  documentation/README.md
  documentation/requirements.txt
  documentation/source/building.rst
  documentation/source/c_symbols.txt
  documentation/source/conf.py
  documentation/source/contributors.rst
  documentation/source/coroutines.rst
  documentation/source/index.rst
  documentation/source/install.rst
  documentation/source/install_devel.rst
  documentation/source/library_reference.rst
  documentation/source/newsfragments/2232.removal.rst
  documentation/source/newsfragments/2289.removal.rst
  documentation/source/newsfragments/2341.change.rst
  documentation/source/newsfragments/913.bugfix.rst
  documentation/source/newsfragments/913.change.rst
  documentation/source/refcard.rst
  documentation/source/regulator.rst
  documentation/source/release_notes.rst
  documentation/source/rescap.rst
  documentation/source/spelling_wordlist.txt
  documentation/source/troubleshooting.rst
  tox.ini
Labels: category:docs

#2420 Alt: Slim down Quickstart by moving details to Writing Testbenches
  documentation/source/quickstart.rst
  documentation/source/writing_testbenches.rst
Labels: category:docs

#2425 Revert behavioral change for 1.5
  cocotb/handle.py
  documentation/source/release_notes.rst
  tests/designs/sample_module/sample_module.sv
  tests/designs/sample_module/sample_module.vhdl
  tests/test_cases/test_cocotb/test_deprecated.py
  tests/test_cases/test_cocotb/test_handle.py
  tests/test_cases/test_multi_dimension_array/test_cocotb_array.py
Labels: type:deprecation
