Repository cocotb/cocotb, pull requests merged in 2021-04, with the labels that each got.

#2501 Log full object name when releasing VHPI handle
  cocotb/share/lib/vhpi/VhpiCbHdl.cpp
Labels: category:codebase:gpi, category:codebase:handle

#2492 Add documentation on how to pass and fail tests
  documentation/source/writing_testbenches.rst
Labels: category:docs, type:feature

#2493 Deprecate setting handle values with __setattr__ syntax
  cocotb/handle.py
  documentation/source/newsfragments/2490.removal.rst
  tests/test_cases/issue_120/issue_120.py
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_array_simple/test_array_simple.py
  tests/test_cases/test_cocotb/test_deprecated.py
  tests/test_cases/test_cocotb/test_handle.py
  tests/test_cases/test_discovery/test_discovery.py
  tests/test_cases/test_force_release/test_force_release.py
  tests/test_cases/test_vhdl_libraries/test_ab.py
Labels: type:deprecation

#2512 Add section about queues to refcard
  documentation/source/refcard.rst
Labels: category:docs

#2504 Fix scheduling issues with start_soon
  cocotb/scheduler.py
  documentation/source/newsfragments/2504.bugfix.rst
  tests/test_cases/test_cocotb/test_concurrency_primitives.py
  tests/test_cases/test_cocotb/test_scheduler.py
Labels: category:codebase:scheduler, type:bug

#2507 Remove RunningTest class
  cocotb/decorators.py
  cocotb/regression.py
  cocotb/scheduler.py
  tests/test_cases/test_cocotb/test_logging.py
Labels: type:cleanup, type:deprecation

#2508 Remove hook
  cocotb/__init__.py
  cocotb/config.py
  cocotb/decorators.py
  cocotb/regression.py
  documentation/source/building.rst
  documentation/source/library_reference.rst
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: type:deprecation

#2523 Fix missing libpython
  cocotb/config.py
  cocotb/share/makefiles/Makefile.inc
Labels: type:bug

#2502 Add custom TRACE logging level below DEBUG.
  cocotb/log.py
  cocotb/share/include/cocotb_utils.h
  cocotb/share/include/gpi_logging.h
  cocotb/share/lib/gpi/GpiCbHdl.cpp
  cocotb/share/lib/gpi_log/gpi_logging.cpp
  documentation/source/building.rst
  documentation/source/newsfragments/2502.change.rst
  tests/test_cases/test_cocotb/test_logging.py
Labels: category:codebase:gpi

#2085 Run test_cocotb with debugging to improve coverage
  Makefile
Labels: category:tests-ci, status:needs-rebase
