Repository cocotb/cocotb, pull requests merged in 2021-09, with the labels that each got.

#2693 Fix small documentation formatting issues
  cocotb/clock.py
  cocotb/decorators.py
  cocotb/triggers.py
  cocotb/utils.py
  documentation/source/library_reference.rst
Labels: category:docs, type:cleanup

#2711 Update docs to use the `sig.value = value` syntax
  README.md
  documentation/source/coroutines.rst
  documentation/source/refcard.rst
  documentation/source/simulator_support.rst
  documentation/source/writing_testbenches.rst
  tests/pytest/test_binary_value.py
  tests/test_cases/test_array_simple/test_array_simple.py
Labels: category:docs

#2717 Change documentation referencing release 2.0 to 1.6
  documentation/source/analog_model.rst
  documentation/source/building.rst
  documentation/source/install.rst
  documentation/source/library_reference.rst
Labels: category:docs, type:cleanup

#2713 Convert fork usage to start and start_soon
  README.md
  cocotb/clock.py
  cocotb/triggers.py
  cocotb/wavedrom.py
  documentation/source/coroutines.rst
  documentation/source/examples.rst
  documentation/source/library_reference.rst
  documentation/source/quickstart.rst
  documentation/source/refcard.rst
  documentation/source/writing_testbenches.rst
  examples/analog_model/afe.py
  examples/analog_model/test_analog_model.py
  examples/matrix_multiplier/tests/test_matrix_multiplier.py
  examples/simple_dff/test_dff.py
  tests/test_cases/issue_120/issue_120.py
  tests/test_cases/issue_142/issue_142.py
  tests/test_cases/issue_348/issue_348.py
  tests/test_cases/issue_588/issue_588.py
  tests/test_cases/issue_892/issue_892.py
  tests/test_cases/issue_957/issue_957.py
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_array_simple/test_array_simple.py
  tests/test_cases/test_cocotb/test_async_coroutines.py
  tests/test_cases/test_cocotb/test_async_generators.py
  tests/test_cases/test_cocotb/test_clock.py
  tests/test_cases/test_cocotb/test_concurrency_primitives.py
  tests/test_cases/test_cocotb/test_edge_triggers.py
  tests/test_cases/test_cocotb/test_generator_coroutines.py
  tests/test_cases/test_cocotb/test_queues.py
  tests/test_cases/test_cocotb/test_scheduler.py
  tests/test_cases/test_cocotb/test_synchronization_primitives.py
  tests/test_cases/test_cocotb/test_timing_triggers.py
  tests/test_cases/test_compare/test_compare.py
  tests/test_cases/test_external/test_external.py
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
  tests/test_cases/test_iteration_vhdl/test_iteration.py
Labels: category:docs, type:cleanup, category:tests-ci, category:codebase:scheduler

#2710 Move code in quickstart doc to its own example
  documentation/source/quickstart.rst
  examples/Makefile
  examples/doc_examples/quickstart/Makefile
  examples/doc_examples/quickstart/my_design.sv
  examples/doc_examples/quickstart/test_my_design.py
  setup.cfg
Labels: category:docs, category:tests-ci

#2678 Replace deprecated distutils
  .github/workflows/regression-tests.yml
  cocotb/_sim_versions.py
  cocotb/_vendor/distutils_version.py
  cocotb/share/makefiles/Makefile.inc
  documentation/source/conf.py
  setup.cfg
  tests/Makefile
Labels: type:cleanup
