Repository cocotb/cocotb, pull requests merged in 2021-03, with the labels that each got.

#2426 Deprecate assigning dict object to signals
  cocotb/handle.py
  documentation/source/release_notes.rst
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: category:codebase:handle, type:deprecation

#2419 Add changes in BinaryValue to support zero vectors
  cocotb/binary.py
  documentation/source/newsfragments/2294.bugfix.rst
  tests/pytest/test_binary_value.py
  tests/test_cases/test_vhdl_zerovector/Makefile
  tests/test_cases/test_vhdl_zerovector/test_vhdl_zerovector.py
  tests/test_cases/test_vhdl_zerovector/vhdl_zerovector.vhdl
Labels: category:codebase:handle

#2439 Add test for Edge(<vector>) with 0/1 bits
  tests/test_cases/test_cocotb/test_edge_triggers.py
Labels: category:tests-ci, status:needs-proprietary-testing

#2468 Reset background color after failed test in summary output
  cocotb/regression.py
Labels: type:cleanup

#2465 Add VHDL library support to questa
  cocotb/share/makefiles/Makefile.sim
  cocotb/share/makefiles/simulators/Makefile.questa
  documentation/source/building.rst
  documentation/source/newsfragments/2465.feature.rst
  tests/test_cases/test_vhdl_libraries/Makefile
  tests/test_cases/test_vhdl_libraries/a.vhdl
  tests/test_cases/test_vhdl_libraries/b.vhdl
  tests/test_cases/test_vhdl_libraries/test_ab.py
Labels: category:codebase:project-automation, category:simulators:questa, status:needs-newsfragment

#2469 Configure pytest to not capture output
  cocotb/__init__.py
  tests/test_cases/test_cocotb/test_pytest.py
Labels: type:bug

#2483 Allow plusargs to have values containing `=`
  cocotb/__init__.py
  documentation/source/newsfragments/2483.bugfix.rst
  tests/designs/plusargs_module/tb_top.v
  tests/test_cases/test_plusargs/Makefile
  tests/test_cases/test_plusargs/plusargs.py
Labels: type:bug

#2428 Make VHPI and FLI blocks look the same as VPI
  documentation/source/diagrams/svg/cocotb_overview.svg
  documentation/source/diagrams/xml/cocotb_overview.xml
Labels: category:docs

#2487 Export COCOTB_RESULTS_FILE make variable
  cocotb/share/makefiles/Makefile.inc
  documentation/source/newsfragments/2487.bugfix.rst
Labels: category:codebase:test-runner, type:bug

#2486 Remove deprecated top-level makefiles
  makefiles/Makefile.inc
  makefiles/Makefile.sim
Labels: type:deprecation
