Repository cocotb/cocotb, pull requests merged in 2021-01, with the labels that each got.

#2324 Fix reference to start_soon() in newsfragment
  documentation/source/newsfragments/2023.feature.rst
Labels: category:docs

#2325 Fix newsfragment for #2091
  documentation/source/newsfragments/2091.change.rst
  documentation/source/newsfragments/2091.changes.rst
Labels: category:docs

#2234 Remove ping TUN TAP example from repo and docs
  documentation/source/diagrams/svg/ping_tun_tap.svg
  documentation/source/diagrams/xml/ping_tun_tap.xml
  documentation/source/index.rst
  documentation/source/newsfragments/2232.removal.rst
  documentation/source/ping_tun_tap.rst
  examples/Makefile
  examples/ping_tun_tap/hdl/icmp_reply.sv
  examples/ping_tun_tap/tests/Makefile
  examples/ping_tun_tap/tests/test_icmp_reply.py
Labels: status:blocked, type:deprecation

#2333 Make vendor dir private
  cocotb/_vendor/__init__.py
  cocotb/_vendor/find_libpython/__init__.py
  cocotb/config.py
  setup.cfg
Labels: type:cleanup

#2331 Make scheduler interfaces private
  cocotb/__init__.py
  cocotb/decorators.py
  cocotb/ipython_support.py
  cocotb/regression.py
  cocotb/scheduler.py
  documentation/source/newsfragments/2278.removal.rst
Labels: type:cleanup

#2322 Add support for SystemVerilog type bit; add test for it
  cocotb/share/lib/vpi/VpiImpl.cpp
  documentation/source/newsfragments/2322.feature.rst
  tests/designs/sample_module/sample_module.sv
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:codebase:gpi, type:feature

#2339 Document the LIBPYTHON_LOC variable
  cocotb/config.py
  cocotb/share/makefiles/Makefile.inc
  documentation/source/building.rst
Labels: category:docs

#2345 Test waiting on both RisingEdge and FallingEdge of a signal simultaneously
  tests/test_cases/test_cocotb/test_edge_triggers.py
Labels: category:tests-ci, status:needs-proprietary-testing

#2348 [Verilator] For debug, build the Verilator interfaces with debug info
  cocotb/share/makefiles/simulators/Makefile.verilator
Labels: category:codebase:project-automation, category:simulators:verilator, type:feature

#2028 Enable assertion rewriting with pytest
  cocotb/__init__.py
  documentation/source/newsfragments/2028.feature.rst
  tests/test_cases/test_cocotb/Makefile
  tests/test_cases/test_cocotb/test_pytest.py
Labels: category:codebase:test-runner, type:feature

#2231 Update test expectations for Riviera-PRO 2020.04/10
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_iteration_vhdl/test_iteration.py
Labels: category:simulators:riviera, category:tests-ci

#2357 Update instructions for installing development version
  documentation/source/install_devel.rst
  documentation/source/quickstart.rst
Labels: category:docs, type:bug

#2343 Improve documentation a bit in several places
  cocotb/config.py
  cocotb/share/makefiles/Makefile.sim
  documentation/source/building.rst
  documentation/source/index.rst
  documentation/source/install.rst
  documentation/source/troubleshooting.rst
Labels: category:docs

#2363 Remove sample_module calls to $display when using Verilator
  tests/designs/sample_module/sample_module.sv
Labels: category:simulators:verilator, category:tests-ci, type:bug

#2374 Update maintainer username
  CONTRIBUTING.md
Labels: category:meta

#2376 Describe relation of HDL and Python types in docs
  documentation/source/quickstart.rst
Labels: category:docs
