Repository cocotb/cocotb, pull requests merged in 2022-05, with the labels that each got.

#2958 Fix leak caused by First
  cocotb/triggers.py
Labels: type:bug, category:codebase:scheduler

#2956 Reformat LICENSE to aid Github detecting it
  LICENSE
Labels: category:meta

#2967 Set level of gpi logger correctly
  cocotb/log.py
Labels: category:codebase:pygpi

#2968 Add Python and library coverage report to end of nox dev_test_* sessions
  noxfile.py
Labels: category:tests-ci

#2971 Fix code coverage reporting
  .codecov.yml
  .github/workflows/regression-tests.yml
Labels: category:tests-ci

#2972 Add comment explaining fetch depth change
  .github/workflows/regression-tests.yml
Labels: category:tests-ci
