Repository cocotb/cocotb, pull requests merged in 2022-03, with the labels that each got.

#2882 Add support for Cadence Xcelium to Python runner
  cocotb/runner.py
  tests/pytest/test_cocotb.py
  tests/pytest/test_runner.py
Labels: category:simulators, category:simulators:xcelium, category:codebase:project-automation

#2896 Show logo in readme
  README.md
Labels: category:docs

#2888 Add support for assigning Logic to handles
  cocotb/handle.py
  tests/test_cases/test_cocotb/test_handle.py
Labels: type:feature, category:codebase:handle

#2895 Include the logo on readthedocs
  documentation/source/_static/cocotb-logo-white.svg
  documentation/source/conf.py
Labels: category:docs

#2902 Fix logo URLs
  README.md
Labels: category:docs

#2905 Doc: Spell out which platforms we support
  documentation/source/index.rst
  documentation/source/platform_support.rst
Labels: category:docs

#2926 CI: Use a version of the GHDL action that works
  .github/workflows/regression-tests.yml
Labels: category:tests-ci
