Repository cocotb/cocotb, pull requests merged in 2023-02, with the labels that each got.

#3045 Do not force division to happen in `float`
  cocotb/clock.py
  documentation/source/newsfragments/3045.feature.rst
  tests/test_cases/test_cocotb/test_clock.py
Labels: type:feature

#3211 Add python runner to examples
  cocotb/runner.py
  examples/adder/tests/test_adder.py
  examples/matrix_multiplier/tests/test_matrix_multiplier.py
  examples/mixed_language/tests/test_mixed_language.py
  examples/simple_dff/test_dff.py
  noxfile.py
  setup.cfg
  tests/benchmark.py
  tests/pytest/test_cocotb.py
  tests/pytest/test_parallel_cocotb.py
  tests/pytest/test_runner.py
  tests/pytest/test_vhdl_libraries_multiple.py
Labels: category:tests-ci, category:codebase:test-runner

#3233 Add python runner plusargs test
  cocotb/runner.py
  tests/pytest/test_plusargs.py
Labels: category:tests-ci, category:codebase:test-runner

#3231 Document minimal Verilator version
  documentation/source/simulator_support.rst
Labels: category:docs, category:simulators:verilator

#3240 [3239] add support for packed struct when using xcelium
  cocotb/share/include/vpi_user_ext.h
  cocotb/share/lib/vpi/VpiImpl.cpp
  documentation/source/newsfragments/3239.bugfix.rst
  tests/test_cases/test_packed_union/Makefile
  tests/test_cases/test_packed_union/test_packed_union.py
  tests/test_cases/test_packed_union/test_packed_union.sv
Labels: category:simulators:xcelium
