Repository cocotb/cocotb, pull requests merged in 2023-11, with the labels that each got.

#3474 Update sv_vpi_user.h to match IEEE 1800-2017
  cocotb/_vendor/vpi/sv_vpi_user.h
Labels: category:codebase:gpi, category:building

#3489 Use a consistent seed in tests/benchmark.py
  tests/benchmark.py
Labels: category:performance

#3487 Scheduler cleanup
  src/cocotb/scheduler.py
Labels: type:cleanup, category:codebase:scheduler

#3491 nox: Cleanup cocotb install for sessions
  noxfile.py
Labels: type:cleanup

#3511 Fix watching code changes for doc live preview
  noxfile.py
Labels: category:docs

#3508 Cleanup startup errors
  src/cocotb/__init__.py
  src/cocotb/regression.py
Labels: type:cleanup, category:codebase:test-runner

#3513 add cocotb.parameterize() similar to nox.parameterize()
  docs/source/library_reference.rst
  docs/source/newsfragments/3513.feature.rst
  src/cocotb/__init__.py
  src/cocotb/decorators.py
  src/cocotb/regression.py
  tests/test_cases/test_cocotb/test_testfactory.py
Labels: type:feature, status:needs-newsfragment
