Repository cocotb/cocotb, pull requests merged in 2023-12, with the labels that each got.

#3554 Update NVC expected results for test_discovery
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:simulators:nvc

#3564 Fix broken newsfrag
  docs/source/newsfragments/2255.bugfix.rst
  docs/source/newsfragments/3427.feature.rst
Labels: category:docs, type:cleanup

#3563 Prevent Edge triggers from being applied to invalid handle types
  src/cocotb/triggers.py
  tests/test_cases/test_cocotb/test_edge_triggers.py
Labels: type:feature, category:codebase:handle

#3570 Disable MSVC test for now
  .github/generate-envs.py
Labels: category:tests-ci

#3567 Fix test_package RTL location
  tests/designs/package_module/Makefile
  tests/test_cases/test_package/Makefile
  tests/test_cases/test_package/cocotb_package.sv
  tests/test_cases/test_package/cocotb_package_pkg.sv
Labels: type:cleanup, category:tests-ci

#3572 Fix documentation issues
  docs/source/examples.rst
Labels: category:docs, type:cleanup

#3568 Add git rev to local version identifier
  .gitignore
  docs/source/newsfragments/3568.feature.rst
  setup.py
  src/cocotb/_version.py
  tests/pytest/test_version.py
Labels: category:packaging

#3571 Move user code coverage feature out of RegressionManager
  src/cocotb/__init__.py
  src/cocotb/regression.py
Labels: type:cleanup, category:codebase:test-runner

#2985 Add support for `vpiPackedArrayNet` type
  src/cocotb/share/lib/vpi/VpiImpl.cpp
Labels: type:feature, category:codebase:gpi
