Repository cocotb/cocotb, pull requests merged in 2024-08, with the labels that each got.

#3974 Make sphinx not generate bogus undocumented return type in autoclass
  docs/source/conf.py
Labels: category:docs

#4110 Fix some documentation issues
  docs/source/install.rst
  docs/source/install_devel.rst
  docs/source/simulator_support.rst
Labels: backport-to:1.9

#4109 Use EXTRA_ARGS correctly in Makefile.verilator
  src/cocotb_tools/makefiles/simulators/Makefile.verilator
Labels: backport-to:1.9

#3624 Simplify VpiArrayObjHdl::initialise
  src/cocotb/share/lib/vpi/VpiObj.cpp
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
Labels: category:codebase:gpi
