Repository cocotb/cocotb, pull requests merged in 2024-11, with the labels that each got.

#4264 Use Python 3.9 as the CI base version (3.8 is EOL)
  .github/generate-envs.py
  .github/workflows/benchmark.yml
Labels: category:ci

#4266 [stable/1.9] Backport PR #4264: Use Python 3.9 as the CI base version (3.8 is EOL)
  .github/generate-envs.py
  .github/workflows/benchmark.yml
Labels: type:backport

#4267 Allow user to specify elaboration arguments for NVC simulator.
  docs/source/newsfragments/4267.feature.rst
  src/cocotb_tools/runner.py
Labels: category:simulators:nvc
