Repository cocotb/cocotb, pull requests merged in 2024-07, with the labels that each got.

#4021 docs: Backport cleanup and fixes
  documentation/source/release_notes.rst
  documentation/source/simulator_support.rst
Labels: category:docs, type:cleanup

#4025 Cleanup `cocotb_tools.runner`
  docs/source/newsfragments/3351.feature.rst
  docs/source/newsfragments/3667.feature.rst
  docs/source/newsfragments/3668.feature.rst
  docs/source/newsfragments/3669.feature.rst
  docs/source/newsfragments/3681.bugfix.rst
  docs/source/newsfragments/3682.bugfix.rst
  docs/source/newsfragments/3683.feature.rst
  docs/source/newsfragments/3744.feature.rst
  docs/source/newsfragments/3796.feature.rst
  docs/source/newsfragments/3836.removal.rst
  docs/source/newsfragments/4025.change.rst
  src/cocotb_tools/py.typed
  src/cocotb_tools/runner.py
  tests/pytest/test_runner.py
Labels: type:cleanup, category:codebase:project-automation

#3938 Remove `cocotb.result.SimFailure`
  docs/source/newsfragments/3938.removal.rst
  docs/source/release_notes.rst
  src/cocotb/__init__.py
  src/cocotb/_scheduler.py
  src/cocotb/decorators.py
  src/cocotb/regression.py
  src/cocotb/result.py
  tests/test_cases/issue_1279/issue_1279.py
  tests/test_cases/test_3316_b/test_3316_b.py
  tests/test_cases/test_3316_d/test_3316_d.py
  tests/test_cases/test_fatal/test_fatal.py
Labels: category:codebase:scheduler

#4028 Fix Riviera-PRO makefile
  src/cocotb_tools/makefiles/simulators/Makefile.riviera
Labels: category:codebase:project-automation

#3983 GpiClock: C++ clock implementation using GPI.
  docs/source/newsfragments/3983.feature.rst
  docs/source/newsfragments/3983.removal.rst
  src/cocotb/clock.py
  src/cocotb/share/lib/simulator/simulatormodule.cpp
  tests/test_cases/test_cocotb/test_clock.py
Labels: type:feature, category:performance, category:codebase:pygpi

#3777 Cleanup handle (Part ??? + 1)
  docs/source/newsfragments/3733.change.1.rst
  docs/source/newsfragments/3733.feature.1.rst
  src/cocotb/handle.py
  tests/designs/vhdl_configurations/testbench.sv
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_cocotb/test_scheduler.py
  tests/test_cases/test_configuration/test_configurations.py
  tests/test_cases/test_discovery/test_discovery.py
  tests/test_cases/test_iteration_mixedlang/test_iteration.py
  tests/test_cases/test_iteration_verilog/test_iteration_es.py
  tests/test_cases/test_iteration_vhdl/test_iteration.py
  tests/test_cases/test_struct/test_struct.py
  tests/test_cases/test_vhdl_access/test_vhdl_access.py
Labels: type:cleanup, category:codebase:handle

#4061 Move profiling out of scheduler
  src/cocotb/__init__.py
  src/cocotb/_profiling.py
  src/cocotb/_scheduler.py
  src/cocotb/regression.py
Labels: type:cleanup, category:performance

#4079 Remove the `data` field from `Event`
  docs/source/newsfragments/4079.removal.rst
  src/cocotb/triggers.py
  tests/test_cases/test_cocotb/test_scheduler.py
  tests/test_cases/test_cocotb/test_synchronization_primitives.py
Labels: category:codebase:scheduler
