Repository cocotb/cocotb, pull requests merged in 2024-03, with the labels that each got.

#3750 Move extensions page from Reference to Howto
  docs/source/index.rst
Labels: category:docs

#3753 Add lru_cache to want_color_output()
  src/cocotb/utils.py
Labels: category:performance

#3751 Add missing `--trace` option to Verilator docs
  docs/source/simulator_support.rst
Labels: category:docs

#3740 Docs: Update Verilator support section
  docs/source/simulator_support.rst
Labels: category:docs, category:simulators:verilator

#3762 Remove remaining uses of COCOTB_SIM
  examples/mixed_language/hdl/endian_swapper.sv
  src/cocotb_tools/makefiles/simulators/Makefile.activehdl
  src/cocotb_tools/makefiles/simulators/Makefile.cvc
  src/cocotb_tools/makefiles/simulators/Makefile.icarus
  src/cocotb_tools/makefiles/simulators/Makefile.questa
  src/cocotb_tools/makefiles/simulators/Makefile.riviera
  src/cocotb_tools/makefiles/simulators/Makefile.vcs
  src/cocotb_tools/makefiles/simulators/Makefile.verilator
  src/cocotb_tools/runner.py
  tests/test_cases/test_iteration_verilog/endian_swapper.sv
Labels: type:cleanup

#3773 CI: Update the codecov GH action to v4
  .github/workflows/regression-tests.yml
Labels: category:tests-ci

#3783 Small typing cleanup of Task and related
  src/cocotb/_outcomes.py
  src/cocotb/task.py
Labels: type:cleanup

#3780 Fix pre-commit bump
  .github/workflows/lint.yml
  .github/workflows/pre-commit-autoupdate.yml
  .pre-commit-config.yaml
Labels: category:tests-ci

#3786 Cleanup after pre-commit autoupdate
  .git-blame-ignore-revs
  examples/mixed_signal/tests/test_regulator_plot.py
  tests/test_cases/test_array/test_array.py
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:ci

#3776 Update tool dependencies in noxfile
  noxfile.py
Labels: category:codebase:project-automation

#3791 Fix help text of combine_results and integrate into cocotb_tools
  Makefile
  src/cocotb_tools/combine_results.py
  tests/test_cases/test_failure/Makefile
  tests/test_cases/test_fatal/Makefile
Labels: type:cleanup, category:ci

#3774 VHPI: Improve get_root_handle()
  docs/source/newsfragments/3774.change.rst
  src/cocotb/share/lib/vhpi/VhpiImpl.cpp
  tests/test_cases/issue_3769/Makefile
Labels: category:codebase:gpi

#3800 Fix small doc linking problems
  docs/source/building.rst
Labels: category:docs

#3799 Remove leftover trace of MEMCHECK envvar
  src/cocotb_tools/config.py
Labels: category:docs

#3802 Doc fixes and cleanup
  docs/source/library_reference.rst
  docs/source/newsfragments/2066.removal.rst
  docs/source/newsfragments/2731.feature.rst
  docs/source/newsfragments/3351.feature.rst
  docs/source/newsfragments/3427.feature.rst
  docs/source/newsfragments/3513.feature.rst
  docs/source/newsfragments/3578.change.rst
  docs/source/newsfragments/3578.removal.rst
  docs/source/newsfragments/3655.feature.1.rst
  docs/source/newsfragments/3655.feature.2.rst
  docs/source/newsfragments/3655.feature.rst
  docs/source/newsfragments/3655.removal.rst
  docs/source/newsfragments/3667.feature.rst
  docs/source/newsfragments/3668.feature.rst
  docs/source/newsfragments/3669.feature.rst
  docs/source/newsfragments/3673.change.rst
  docs/source/newsfragments/3681.bugfix.rst
  docs/source/newsfragments/3682.bugfix.rst
  docs/source/newsfragments/3683.feature.rst
  docs/source/newsfragments/3717.feature.rst
  docs/source/newsfragments/3717.removal.rst
  docs/source/newsfragments/3744.feature.rst
  docs/source/release_notes.rst
  docs/source/simulator_support.rst
  docs/source/troubleshooting.rst
  src/cocotb/__init__.py
  src/cocotb/decorators.py
  src/cocotb/handle.py
  src/cocotb_tools/runner.py
Labels: category:docs

#3817 VPI: Use iteration fallback when looking for vpiGenScope by name
  docs/source/newsfragments/3817.feature.rst
  src/cocotb/share/lib/vpi/VpiImpl.cpp
  tests/test_cases/test_discovery/test_discovery.py
Labels: type:feature, category:simulators:questa, category:simulators:verilator, category:codebase:gpi
