Repository cocotb/cocotb, pull requests merged in 2024-06, with the labels that each got.

#3798 Document COVERAGE_RCFILE
  docs/source/building.rst
  src/cocotb_tools/config.py
Labels: category:docs

#3986 Verilator: Don't run interface array tests on versions earlier than v5.024
  tests/test_cases/test_sv_interface/test_sv_if.py
Labels: category:ci, category:simulators:verilator

#3988 CI: Update NVC to latest release 1.12.2
  .github/generate-envs.py
Labels: category:ci, category:simulators:nvc

#3987 Improve TypeError exception message for edge triggers
  src/cocotb/triggers.py
Labels: type:cleanup, category:codebase:scheduler, category:codebase:handle

#3991 docs: Add NullTrigger to Python Triggers section
  docs/source/library_reference.rst
Labels: category:docs

#3992 CI: Use case-insensitive regex match for repr strings that contain handle paths
  tests/test_cases/test_cocotb/test_edge_triggers.py
Labels: type:cleanup, category:ci
