Repository cocotb/cocotb, pull requests merged in 2024-02, with the labels that each got.

#3618 Validate the pyproject.toml file in pre-commit
  .pre-commit-config.yaml
Labels: category:tests-ci

#3719 Remove unused Queue._finished Event
  src/cocotb/queue.py
Labels: type:cleanup

#3729 Add more integer parameters to test_package
  tests/test_cases/test_package/cocotb_package_pkg.sv
  tests/test_cases/test_package/test_package.py
Labels: category:codebase:gpi

#3739 CI: Update pinned Verilator version to latest release
  .github/generate-envs.py
Labels: category:tests-ci

#3737 Split VpiCbHdl.cpp (with history)
  cocotb_build_libs.py
  src/cocotb/share/lib/vpi/VpiCbHdl.cpp
  src/cocotb/share/lib/vpi/VpiIterator.cpp
  src/cocotb/share/lib/vpi/VpiObj.cpp
  src/cocotb/share/lib/vpi/VpiSignal.cpp
Labels: type:cleanup, category:codebase:gpi
