Repository cocotb/cocotb, pull requests merged in 2025-02, with the labels that each got.

#4418 Make heading format of release notes more consistent
  docs/source/release_notes.rst
Labels: category:docs

#4437 Add TestSuccess and ValueChange to Library Reference
  docs/source/library_reference.rst
  src/cocotb/triggers.py
Labels: category:docs

#4433 Add sphinx-codeautolink extension
  docs/requirements.txt
  docs/source/_static/cocotb.css
  docs/source/conf.py
  docs/source/coroutines.rst
  docs/source/extensions.rst
  docs/source/library_reference.rst
  docs/source/quickstart.rst
  docs/source/release_notes.rst
  docs/source/rotating_logger.rst
  docs/source/runner.rst
  docs/source/simulator_support.rst
  docs/source/triggers.rst
  docs/source/writing_testbenches.rst
  src/cocotb/_decorators.py
  src/cocotb/_utils.py
  src/cocotb/handle.py
  src/cocotb/task.py
  src/cocotb/triggers.py
  src/cocotb/types/array.py
  src/cocotb/types/logic.py
  src/cocotb/types/logic_array.py
  src/cocotb/types/range.py
  src/cocotb_tools/runner.py
Labels: category:docs

#4440 Link more objects in docs
  docs/source/runner.rst
  docs/source/writing_testbenches.rst
Labels: category:docs

#4447 Add missing word; add reference to glossary
  docs/source/runner.rst
Labels: category:docs

#4446 Take green color for e.g. versionadded from docs.python.org
  docs/source/_static/cocotb.css
Labels: category:docs

#4452 Fix broken VCS tests
  noxfile.py
Labels: type:bug, category:ci

#4450 pin Ubuntu version in CI
  .github/generate-envs.py
Labels: type:bug, category:ci

#4451 Split `cocotb.triggers`
  src/cocotb/_base_triggers.py
  src/cocotb/_extended_awaitables.py
  src/cocotb/_gpi_triggers.py
  src/cocotb/_scheduler.py
  src/cocotb/_utils.py
  src/cocotb/handle.py
  src/cocotb/queue.py
  src/cocotb/triggers.py
  tests/test_cases/test_cocotb/test_synchronization_primitives.py
Labels: type:cleanup

#4449 Fix leak of waiters in `Combine`
  src/cocotb/_extended_awaitables.py
  tests/test_cases/test_cocotb/test_synchronization_primitives.py
Labels: type:bug, category:codebase:scheduler

#4471 Update documentation on repo labels
  docs/source/maintaining.rst
Labels: category:docs, type:cleanup

#4481 Fix VPI issuing error incorrectly
  src/cocotb/share/lib/vpi/VpiImpl.cpp
Labels: type:bug, category:codebase:gpi

#4478 Fix computation of results_xml_file in Python runner
  src/cocotb_tools/runner.py
Labels: type:bug, category:codebase:project-automation

#4463 Raise logging level of exceptions from tests
  docs/source/newsfragments/4463.change.rst
  src/cocotb/regression.py
Labels: category:codebase:tests

#4505 Makefile cleanup
  docs/source/newsfragments/4505.feature.rst
  src/cocotb_tools/makefiles/Makefile.inc
  src/cocotb_tools/makefiles/simulators/Makefile.activehdl
  src/cocotb_tools/makefiles/simulators/Makefile.cvc
  src/cocotb_tools/makefiles/simulators/Makefile.ghdl
  src/cocotb_tools/makefiles/simulators/Makefile.icarus
  src/cocotb_tools/makefiles/simulators/Makefile.ius
  src/cocotb_tools/makefiles/simulators/Makefile.nvc
  src/cocotb_tools/makefiles/simulators/Makefile.questa
  src/cocotb_tools/makefiles/simulators/Makefile.riviera
  src/cocotb_tools/makefiles/simulators/Makefile.vcs
  src/cocotb_tools/makefiles/simulators/Makefile.verilator
  src/cocotb_tools/makefiles/simulators/Makefile.xcelium
Labels: type:feature, category:codebase:project-automation, type:change

#4513 Rename `PYGPI_ENTRY_POINT` to `PYGPI_USERS`
  docs/source/building.rst
  docs/source/newsfragments/4310.change.1.rst
  docs/source/newsfragments/4310.change.rst
  docs/source/newsfragments/4310.feature.rst
  docs/source/newsfragments/4513.change.rst
  src/pygpi/entry.py
  tests/test_cases/test_custom_entry/Makefile
Labels: category:codebase:gpi, type:change

#4490 Reimplement Queues
  src/cocotb/queue.py
Labels: type:bug, category:codebase:utils

#4489 Fix issue with clock
  src/cocotb/clock.py
Labels: type:bug, category:codebase:utils

#4499 Cleanup/Fix leak in simulatormodule.cpp
  src/cocotb/share/lib/simulator/simulatormodule.cpp
Labels: type:bug, type:cleanup, category:codebase:pygpi
