Repository cocotb/cocotb, pull requests merged in 2025-05, with the labels that each got.

#4628 Make `CancellationError` a `RuntimeError`
  src/cocotb/task.py
  tests/test_cases/test_cocotb/test_scheduler.py
Labels: type:change, category:codebase:tasks

#4644 Bump minimum Verilator version support to 5.036
  .github/generate-envs.py
  docs/source/newsfragments/4644.change.rst
  docs/source/simulator_support.rst
  tests/test_cases/test_array_simple/test_array_simple.py
  tests/test_cases/test_discovery/test_discovery.py
Labels: category:docs, category:ci, type:change

#4587 Add test for issue #376
  tests/test_cases/test_cocotb/test_edge_triggers.py
Labels: type:bug, category:simulators:questa

#4678 [stable/1.9] Backport PR #4570: Switch private CI to Ubuntu 22.04
  .github/generate-envs.py
Labels: type:backport

#4684 Revert Test Discovery Change (part 1)
  docs/source/conf.py
  docs/source/library_reference.rst
  docs/source/newsfragments/3513.feature.rst
  docs/source/newsfragments/3717.feature.1.rst
  docs/source/newsfragments/3717.feature.rst
  docs/source/newsfragments/3717.removal.rst
  docs/source/newsfragments/3938.removal.rst
  docs/source/newsfragments/4477.feature.rst
  docs/source/newsfragments/4477.removal.rst
  docs/source/refcard.rst
  docs/source/writing_testbenches.rst
  src/cocotb/__init__.py
  src/cocotb/_decorators.py
  src/cocotb/_test.py
  src/cocotb/_test_factory.py
  src/cocotb/regression.py
  tests/pytest/test_parameterize.py
  tests/test_cases/issue_1279/issue_1279.py
  tests/test_cases/test_3316_b/test_3316_b.py
  tests/test_cases/test_3316_d/test_3316_d.py
  tests/test_cases/test_cocotb/test_clock.py
  tests/test_cases/test_cocotb/test_handle.py
  tests/test_cases/test_cocotb/test_queues.py
  tests/test_cases/test_cocotb/test_testfactory.py
  tests/test_cases/test_cocotb/test_tests.py
  tests/test_cases/test_fatal/test_fatal.py
  tests/test_cases/test_kill_sim/kill_sim_tests.py
Labels: type:cleanup, category:codebase:tests, type:change

#4697 Add deprecated re-exports to `cocotb.results`
  docs/source/library_reference.rst
  docs/source/newsfragments/4685.change.rst
  src/cocotb/result.py
  tests/test_cases/test_cocotb/test_deprecated.py
Labels: type:cleanup
